// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ranking.proto

package ranking

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import empty "github.com/golang/protobuf/ptypes/empty"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ChainMeta struct {
	Height               string   `protobuf:"bytes,1,opt,name=height,proto3" json:"height,omitempty"`
	TotalCandidates      uint64   `protobuf:"varint,2,opt,name=totalCandidates,proto3" json:"totalCandidates,omitempty"`
	TotalVotedStakes     string   `protobuf:"bytes,3,opt,name=totalVotedStakes,proto3" json:"totalVotedStakes,omitempty"`
	TotalVotes           string   `protobuf:"bytes,4,opt,name=totalVotes,proto3" json:"totalVotes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChainMeta) Reset()         { *m = ChainMeta{} }
func (m *ChainMeta) String() string { return proto.CompactTextString(m) }
func (*ChainMeta) ProtoMessage()    {}
func (*ChainMeta) Descriptor() ([]byte, []int) {
	return fileDescriptor_ranking_723b6fafc7401965, []int{0}
}
func (m *ChainMeta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChainMeta.Unmarshal(m, b)
}
func (m *ChainMeta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChainMeta.Marshal(b, m, deterministic)
}
func (dst *ChainMeta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChainMeta.Merge(dst, src)
}
func (m *ChainMeta) XXX_Size() int {
	return xxx_messageInfo_ChainMeta.Size(m)
}
func (m *ChainMeta) XXX_DiscardUnknown() {
	xxx_messageInfo_ChainMeta.DiscardUnknown(m)
}

var xxx_messageInfo_ChainMeta proto.InternalMessageInfo

func (m *ChainMeta) GetHeight() string {
	if m != nil {
		return m.Height
	}
	return ""
}

func (m *ChainMeta) GetTotalCandidates() uint64 {
	if m != nil {
		return m.TotalCandidates
	}
	return 0
}

func (m *ChainMeta) GetTotalVotedStakes() string {
	if m != nil {
		return m.TotalVotedStakes
	}
	return ""
}

func (m *ChainMeta) GetTotalVotes() string {
	if m != nil {
		return m.TotalVotes
	}
	return ""
}

type Bucket struct {
	// hex string
	Voter         string `protobuf:"bytes,1,opt,name=voter,proto3" json:"voter,omitempty"`
	Votes         string `protobuf:"bytes,2,opt,name=votes,proto3" json:"votes,omitempty"`
	WeightedVotes string `protobuf:"bytes,3,opt,name=weightedVotes,proto3" json:"weightedVotes,omitempty"`
	// human readable duration
	RemainingDuration    string   `protobuf:"bytes,4,opt,name=remainingDuration,proto3" json:"remainingDuration,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Bucket) Reset()         { *m = Bucket{} }
func (m *Bucket) String() string { return proto.CompactTextString(m) }
func (*Bucket) ProtoMessage()    {}
func (*Bucket) Descriptor() ([]byte, []int) {
	return fileDescriptor_ranking_723b6fafc7401965, []int{1}
}
func (m *Bucket) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Bucket.Unmarshal(m, b)
}
func (m *Bucket) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Bucket.Marshal(b, m, deterministic)
}
func (dst *Bucket) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Bucket.Merge(dst, src)
}
func (m *Bucket) XXX_Size() int {
	return xxx_messageInfo_Bucket.Size(m)
}
func (m *Bucket) XXX_DiscardUnknown() {
	xxx_messageInfo_Bucket.DiscardUnknown(m)
}

var xxx_messageInfo_Bucket proto.InternalMessageInfo

func (m *Bucket) GetVoter() string {
	if m != nil {
		return m.Voter
	}
	return ""
}

func (m *Bucket) GetVotes() string {
	if m != nil {
		return m.Votes
	}
	return ""
}

func (m *Bucket) GetWeightedVotes() string {
	if m != nil {
		return m.WeightedVotes
	}
	return ""
}

func (m *Bucket) GetRemainingDuration() string {
	if m != nil {
		return m.RemainingDuration
	}
	return ""
}

type Candidate struct {
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// hex string
	Address              string   `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	TotalWeightedVotes   string   `protobuf:"bytes,3,opt,name=totalWeightedVotes,proto3" json:"totalWeightedVotes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Candidate) Reset()         { *m = Candidate{} }
func (m *Candidate) String() string { return proto.CompactTextString(m) }
func (*Candidate) ProtoMessage()    {}
func (*Candidate) Descriptor() ([]byte, []int) {
	return fileDescriptor_ranking_723b6fafc7401965, []int{2}
}
func (m *Candidate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Candidate.Unmarshal(m, b)
}
func (m *Candidate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Candidate.Marshal(b, m, deterministic)
}
func (dst *Candidate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Candidate.Merge(dst, src)
}
func (m *Candidate) XXX_Size() int {
	return xxx_messageInfo_Candidate.Size(m)
}
func (m *Candidate) XXX_DiscardUnknown() {
	xxx_messageInfo_Candidate.DiscardUnknown(m)
}

var xxx_messageInfo_Candidate proto.InternalMessageInfo

func (m *Candidate) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Candidate) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Candidate) GetTotalWeightedVotes() string {
	if m != nil {
		return m.TotalWeightedVotes
	}
	return ""
}

type GetCandidatesRequest struct {
	Height               string   `protobuf:"bytes,1,opt,name=height,proto3" json:"height,omitempty"`
	Offset               uint32   `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit                uint32   `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCandidatesRequest) Reset()         { *m = GetCandidatesRequest{} }
func (m *GetCandidatesRequest) String() string { return proto.CompactTextString(m) }
func (*GetCandidatesRequest) ProtoMessage()    {}
func (*GetCandidatesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ranking_723b6fafc7401965, []int{3}
}
func (m *GetCandidatesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCandidatesRequest.Unmarshal(m, b)
}
func (m *GetCandidatesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCandidatesRequest.Marshal(b, m, deterministic)
}
func (dst *GetCandidatesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCandidatesRequest.Merge(dst, src)
}
func (m *GetCandidatesRequest) XXX_Size() int {
	return xxx_messageInfo_GetCandidatesRequest.Size(m)
}
func (m *GetCandidatesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCandidatesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetCandidatesRequest proto.InternalMessageInfo

func (m *GetCandidatesRequest) GetHeight() string {
	if m != nil {
		return m.Height
	}
	return ""
}

func (m *GetCandidatesRequest) GetOffset() uint32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *GetCandidatesRequest) GetLimit() uint32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type GetBucketsByCandidateRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Height               string   `protobuf:"bytes,2,opt,name=height,proto3" json:"height,omitempty"`
	Offset               uint32   `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit                uint32   `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBucketsByCandidateRequest) Reset()         { *m = GetBucketsByCandidateRequest{} }
func (m *GetBucketsByCandidateRequest) String() string { return proto.CompactTextString(m) }
func (*GetBucketsByCandidateRequest) ProtoMessage()    {}
func (*GetBucketsByCandidateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ranking_723b6fafc7401965, []int{4}
}
func (m *GetBucketsByCandidateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBucketsByCandidateRequest.Unmarshal(m, b)
}
func (m *GetBucketsByCandidateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBucketsByCandidateRequest.Marshal(b, m, deterministic)
}
func (dst *GetBucketsByCandidateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBucketsByCandidateRequest.Merge(dst, src)
}
func (m *GetBucketsByCandidateRequest) XXX_Size() int {
	return xxx_messageInfo_GetBucketsByCandidateRequest.Size(m)
}
func (m *GetBucketsByCandidateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBucketsByCandidateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetBucketsByCandidateRequest proto.InternalMessageInfo

func (m *GetBucketsByCandidateRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GetBucketsByCandidateRequest) GetHeight() string {
	if m != nil {
		return m.Height
	}
	return ""
}

func (m *GetBucketsByCandidateRequest) GetOffset() uint32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *GetBucketsByCandidateRequest) GetLimit() uint32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type CandidateResponse struct {
	Candidates           []*Candidate `protobuf:"bytes,1,rep,name=candidates,proto3" json:"candidates,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *CandidateResponse) Reset()         { *m = CandidateResponse{} }
func (m *CandidateResponse) String() string { return proto.CompactTextString(m) }
func (*CandidateResponse) ProtoMessage()    {}
func (*CandidateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ranking_723b6fafc7401965, []int{5}
}
func (m *CandidateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CandidateResponse.Unmarshal(m, b)
}
func (m *CandidateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CandidateResponse.Marshal(b, m, deterministic)
}
func (dst *CandidateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CandidateResponse.Merge(dst, src)
}
func (m *CandidateResponse) XXX_Size() int {
	return xxx_messageInfo_CandidateResponse.Size(m)
}
func (m *CandidateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CandidateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CandidateResponse proto.InternalMessageInfo

func (m *CandidateResponse) GetCandidates() []*Candidate {
	if m != nil {
		return m.Candidates
	}
	return nil
}

type BucketResponse struct {
	Buckets              []*Bucket `protobuf:"bytes,1,rep,name=buckets,proto3" json:"buckets,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *BucketResponse) Reset()         { *m = BucketResponse{} }
func (m *BucketResponse) String() string { return proto.CompactTextString(m) }
func (*BucketResponse) ProtoMessage()    {}
func (*BucketResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ranking_723b6fafc7401965, []int{6}
}
func (m *BucketResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BucketResponse.Unmarshal(m, b)
}
func (m *BucketResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BucketResponse.Marshal(b, m, deterministic)
}
func (dst *BucketResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BucketResponse.Merge(dst, src)
}
func (m *BucketResponse) XXX_Size() int {
	return xxx_messageInfo_BucketResponse.Size(m)
}
func (m *BucketResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BucketResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BucketResponse proto.InternalMessageInfo

func (m *BucketResponse) GetBuckets() []*Bucket {
	if m != nil {
		return m.Buckets
	}
	return nil
}

func init() {
	proto.RegisterType((*ChainMeta)(nil), "ranking.ChainMeta")
	proto.RegisterType((*Bucket)(nil), "ranking.Bucket")
	proto.RegisterType((*Candidate)(nil), "ranking.Candidate")
	proto.RegisterType((*GetCandidatesRequest)(nil), "ranking.GetCandidatesRequest")
	proto.RegisterType((*GetBucketsByCandidateRequest)(nil), "ranking.GetBucketsByCandidateRequest")
	proto.RegisterType((*CandidateResponse)(nil), "ranking.CandidateResponse")
	proto.RegisterType((*BucketResponse)(nil), "ranking.BucketResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RankingClient is the client API for Ranking service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RankingClient interface {
	// get the blockchain meta data
	GetMeta(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*ChainMeta, error)
	// get candidates
	GetCandidates(ctx context.Context, in *GetCandidatesRequest, opts ...grpc.CallOption) (*CandidateResponse, error)
	// get buckets by candidate
	GetBucketsByCandidate(ctx context.Context, in *GetBucketsByCandidateRequest, opts ...grpc.CallOption) (*BucketResponse, error)
}

type rankingClient struct {
	cc *grpc.ClientConn
}

func NewRankingClient(cc *grpc.ClientConn) RankingClient {
	return &rankingClient{cc}
}

func (c *rankingClient) GetMeta(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*ChainMeta, error) {
	out := new(ChainMeta)
	err := c.cc.Invoke(ctx, "/ranking.Ranking/getMeta", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rankingClient) GetCandidates(ctx context.Context, in *GetCandidatesRequest, opts ...grpc.CallOption) (*CandidateResponse, error) {
	out := new(CandidateResponse)
	err := c.cc.Invoke(ctx, "/ranking.Ranking/getCandidates", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rankingClient) GetBucketsByCandidate(ctx context.Context, in *GetBucketsByCandidateRequest, opts ...grpc.CallOption) (*BucketResponse, error) {
	out := new(BucketResponse)
	err := c.cc.Invoke(ctx, "/ranking.Ranking/getBucketsByCandidate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RankingServer is the server API for Ranking service.
type RankingServer interface {
	// get the blockchain meta data
	GetMeta(context.Context, *empty.Empty) (*ChainMeta, error)
	// get candidates
	GetCandidates(context.Context, *GetCandidatesRequest) (*CandidateResponse, error)
	// get buckets by candidate
	GetBucketsByCandidate(context.Context, *GetBucketsByCandidateRequest) (*BucketResponse, error)
}

func RegisterRankingServer(s *grpc.Server, srv RankingServer) {
	s.RegisterService(&_Ranking_serviceDesc, srv)
}

func _Ranking_GetMeta_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RankingServer).GetMeta(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ranking.Ranking/GetMeta",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RankingServer).GetMeta(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ranking_GetCandidates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCandidatesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RankingServer).GetCandidates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ranking.Ranking/GetCandidates",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RankingServer).GetCandidates(ctx, req.(*GetCandidatesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ranking_GetBucketsByCandidate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBucketsByCandidateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RankingServer).GetBucketsByCandidate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ranking.Ranking/GetBucketsByCandidate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RankingServer).GetBucketsByCandidate(ctx, req.(*GetBucketsByCandidateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Ranking_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ranking.Ranking",
	HandlerType: (*RankingServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "getMeta",
			Handler:    _Ranking_GetMeta_Handler,
		},
		{
			MethodName: "getCandidates",
			Handler:    _Ranking_GetCandidates_Handler,
		},
		{
			MethodName: "getBucketsByCandidate",
			Handler:    _Ranking_GetBucketsByCandidate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ranking.proto",
}

func init() { proto.RegisterFile("ranking.proto", fileDescriptor_ranking_723b6fafc7401965) }

var fileDescriptor_ranking_723b6fafc7401965 = []byte{
	// 461 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x53, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0xae, 0x9b, 0x10, 0x2b, 0x83, 0x4c, 0xe9, 0xa8, 0x14, 0xcb, 0xfc, 0x28, 0xb2, 0x40, 0x0a,
	0x08, 0xb9, 0x52, 0x38, 0x70, 0xe0, 0xd6, 0x82, 0x72, 0x81, 0x8b, 0x91, 0x40, 0x48, 0x5c, 0x36,
	0xf5, 0xc4, 0x59, 0x25, 0xd9, 0x0d, 0xde, 0x09, 0xd0, 0x37, 0xe0, 0x15, 0x78, 0x46, 0x5e, 0x02,
	0x75, 0x77, 0xed, 0x98, 0xd6, 0xb9, 0x79, 0xbe, 0x19, 0x7d, 0x3f, 0x9e, 0x1d, 0x88, 0x2a, 0xa1,
	0x96, 0x52, 0x95, 0xd9, 0xa6, 0xd2, 0xac, 0x31, 0xf4, 0x65, 0xf2, 0xa8, 0xd4, 0xba, 0x5c, 0xd1,
	0x99, 0x85, 0x67, 0xdb, 0xf9, 0x19, 0xad, 0x37, 0x7c, 0xe5, 0xa6, 0xd2, 0x3f, 0x01, 0x0c, 0x2f,
	0x16, 0x42, 0xaa, 0x8f, 0xc4, 0x02, 0x4f, 0x61, 0xb0, 0x20, 0x59, 0x2e, 0x38, 0x0e, 0x46, 0xc1,
	0x78, 0x98, 0xfb, 0x0a, 0xc7, 0x70, 0xc4, 0x9a, 0xc5, 0xea, 0x42, 0xa8, 0x42, 0x16, 0x82, 0xc9,
	0xc4, 0x87, 0xa3, 0x60, 0xdc, 0xcf, 0x6f, 0xc2, 0xf8, 0x12, 0xee, 0x5b, 0xe8, 0xb3, 0x66, 0x2a,
	0x3e, 0xb1, 0x58, 0x92, 0x89, 0x7b, 0x96, 0xeb, 0x16, 0x8e, 0x4f, 0x01, 0x1a, 0xcc, 0xc4, 0x7d,
	0x3b, 0xd5, 0x42, 0xd2, 0xdf, 0x01, 0x0c, 0xce, 0xb7, 0x97, 0x4b, 0x62, 0x3c, 0x81, 0x3b, 0x3f,
	0x34, 0x53, 0xe5, 0x7d, 0xb9, 0xa2, 0x46, 0x9d, 0x19, 0x8f, 0x1a, 0x7c, 0x06, 0xd1, 0x4f, 0x6b,
	0x9b, 0x0a, 0xc7, 0xec, 0xf4, 0xff, 0x07, 0xf1, 0x15, 0x1c, 0x57, 0xb4, 0x16, 0x52, 0x49, 0x55,
	0xbe, 0xdb, 0x56, 0x82, 0xa5, 0x56, 0xde, 0xc3, 0xed, 0x46, 0x2a, 0x61, 0xd8, 0x84, 0x44, 0x84,
	0xbe, 0x12, 0x6b, 0xf2, 0x5e, 0xec, 0x37, 0xc6, 0x10, 0x8a, 0xa2, 0xa8, 0xc8, 0xd4, 0x66, 0xea,
	0x12, 0x33, 0x40, 0x9b, 0xe9, 0x4b, 0x87, 0xa7, 0x8e, 0x4e, 0xfa, 0x0d, 0x4e, 0xa6, 0xc4, 0xbb,
	0x5f, 0x9a, 0xd3, 0xf7, 0x2d, 0x19, 0xde, 0xbb, 0x9b, 0x53, 0x18, 0xe8, 0xf9, 0xdc, 0x10, 0x5b,
	0xe1, 0x28, 0xf7, 0xd5, 0xf5, 0xcf, 0x59, 0xc9, 0xb5, 0x64, 0x2b, 0x15, 0xe5, 0xae, 0x48, 0x7f,
	0xc1, 0xe3, 0x29, 0xb1, 0xfb, 0xab, 0xe6, 0xfc, 0xaa, 0x91, 0xa9, 0x55, 0xba, 0xb2, 0xed, 0x94,
	0x0f, 0xf7, 0x28, 0xf7, 0xba, 0x95, 0xfb, 0x6d, 0xe5, 0x29, 0x1c, 0xb7, 0xd4, 0xcc, 0x46, 0x2b,
	0x43, 0x38, 0x01, 0xb8, 0xdc, 0xbd, 0xa9, 0x60, 0xd4, 0x1b, 0xdf, 0x9d, 0x60, 0x56, 0x3f, 0xe4,
	0xdd, 0x7c, 0x6b, 0x2a, 0x7d, 0x0b, 0xf7, 0x9c, 0xff, 0x86, 0xe5, 0x05, 0x84, 0x33, 0x97, 0xc8,
	0x53, 0x1c, 0x35, 0x14, 0x7e, 0xb2, 0xee, 0x4f, 0xfe, 0x06, 0x10, 0xe6, 0xae, 0x87, 0x6f, 0x20,
	0x2c, 0x89, 0xdd, 0xc3, 0xcf, 0xdc, 0x91, 0x64, 0xf5, 0x91, 0x64, 0xef, 0xaf, 0x8f, 0x24, 0x69,
	0x79, 0xa9, 0x8f, 0x24, 0x3d, 0xc0, 0x0f, 0x10, 0x95, 0xed, 0x15, 0xe1, 0x93, 0x66, 0xac, 0x6b,
	0x75, 0x49, 0xd2, 0x91, 0xc8, 0x7b, 0x4f, 0x0f, 0xf0, 0x2b, 0x3c, 0x28, 0xbb, 0x56, 0x82, 0xcf,
	0xdb, 0xac, 0x7b, 0x57, 0x96, 0x3c, 0xbc, 0x19, 0xb6, 0xa1, 0x9e, 0x0d, 0x6c, 0x9c, 0xd7, 0xff,
	0x02, 0x00, 0x00, 0xff, 0xff, 0x47, 0xc8, 0x46, 0x7b, 0x1b, 0x04, 0x00, 0x00,
}
