// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ranking.proto

package ranking

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type HealthCheckResponse_Status int32

const (
	HealthCheckResponse_STARTING HealthCheckResponse_Status = 0
	HealthCheckResponse_ACTIVE   HealthCheckResponse_Status = 1
	HealthCheckResponse_INACTIVE HealthCheckResponse_Status = 2
)

var HealthCheckResponse_Status_name = map[int32]string{
	0: "STARTING",
	1: "ACTIVE",
	2: "INACTIVE",
}

var HealthCheckResponse_Status_value = map[string]int32{
	"STARTING": 0,
	"ACTIVE":   1,
	"INACTIVE": 2,
}

func (x HealthCheckResponse_Status) String() string {
	return proto.EnumName(HealthCheckResponse_Status_name, int32(x))
}

func (HealthCheckResponse_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_097e8f966f16a890, []int{5, 0}
}

type ChainMeta struct {
	Height               string   `protobuf:"bytes,1,opt,name=height,proto3" json:"height,omitempty"`
	TotalCandidates      uint64   `protobuf:"varint,2,opt,name=totalCandidates,proto3" json:"totalCandidates,omitempty"`
	TotalVotedStakes     string   `protobuf:"bytes,3,opt,name=totalVotedStakes,proto3" json:"totalVotedStakes,omitempty"`
	TotalVotes           string   `protobuf:"bytes,4,opt,name=totalVotes,proto3" json:"totalVotes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChainMeta) Reset()         { *m = ChainMeta{} }
func (m *ChainMeta) String() string { return proto.CompactTextString(m) }
func (*ChainMeta) ProtoMessage()    {}
func (*ChainMeta) Descriptor() ([]byte, []int) {
	return fileDescriptor_097e8f966f16a890, []int{0}
}

func (m *ChainMeta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChainMeta.Unmarshal(m, b)
}
func (m *ChainMeta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChainMeta.Marshal(b, m, deterministic)
}
func (m *ChainMeta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChainMeta.Merge(m, src)
}
func (m *ChainMeta) XXX_Size() int {
	return xxx_messageInfo_ChainMeta.Size(m)
}
func (m *ChainMeta) XXX_DiscardUnknown() {
	xxx_messageInfo_ChainMeta.DiscardUnknown(m)
}

var xxx_messageInfo_ChainMeta proto.InternalMessageInfo

func (m *ChainMeta) GetHeight() string {
	if m != nil {
		return m.Height
	}
	return ""
}

func (m *ChainMeta) GetTotalCandidates() uint64 {
	if m != nil {
		return m.TotalCandidates
	}
	return 0
}

func (m *ChainMeta) GetTotalVotedStakes() string {
	if m != nil {
		return m.TotalVotedStakes
	}
	return ""
}

func (m *ChainMeta) GetTotalVotes() string {
	if m != nil {
		return m.TotalVotes
	}
	return ""
}

type Bucket struct {
	// hex string
	Voter         string `protobuf:"bytes,1,opt,name=voter,proto3" json:"voter,omitempty"`
	Votes         string `protobuf:"bytes,2,opt,name=votes,proto3" json:"votes,omitempty"`
	WeightedVotes string `protobuf:"bytes,3,opt,name=weightedVotes,proto3" json:"weightedVotes,omitempty"`
	// human readable duration
	RemainingDuration    string   `protobuf:"bytes,4,opt,name=remainingDuration,proto3" json:"remainingDuration,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Bucket) Reset()         { *m = Bucket{} }
func (m *Bucket) String() string { return proto.CompactTextString(m) }
func (*Bucket) ProtoMessage()    {}
func (*Bucket) Descriptor() ([]byte, []int) {
	return fileDescriptor_097e8f966f16a890, []int{1}
}

func (m *Bucket) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Bucket.Unmarshal(m, b)
}
func (m *Bucket) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Bucket.Marshal(b, m, deterministic)
}
func (m *Bucket) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Bucket.Merge(m, src)
}
func (m *Bucket) XXX_Size() int {
	return xxx_messageInfo_Bucket.Size(m)
}
func (m *Bucket) XXX_DiscardUnknown() {
	xxx_messageInfo_Bucket.DiscardUnknown(m)
}

var xxx_messageInfo_Bucket proto.InternalMessageInfo

func (m *Bucket) GetVoter() string {
	if m != nil {
		return m.Voter
	}
	return ""
}

func (m *Bucket) GetVotes() string {
	if m != nil {
		return m.Votes
	}
	return ""
}

func (m *Bucket) GetWeightedVotes() string {
	if m != nil {
		return m.WeightedVotes
	}
	return ""
}

func (m *Bucket) GetRemainingDuration() string {
	if m != nil {
		return m.RemainingDuration
	}
	return ""
}

type Candidate struct {
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// hex string
	Address              string   `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	TotalWeightedVotes   string   `protobuf:"bytes,3,opt,name=totalWeightedVotes,proto3" json:"totalWeightedVotes,omitempty"`
	SelfStakingTokens    string   `protobuf:"bytes,4,opt,name=SelfStakingTokens,proto3" json:"SelfStakingTokens,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Candidate) Reset()         { *m = Candidate{} }
func (m *Candidate) String() string { return proto.CompactTextString(m) }
func (*Candidate) ProtoMessage()    {}
func (*Candidate) Descriptor() ([]byte, []int) {
	return fileDescriptor_097e8f966f16a890, []int{2}
}

func (m *Candidate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Candidate.Unmarshal(m, b)
}
func (m *Candidate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Candidate.Marshal(b, m, deterministic)
}
func (m *Candidate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Candidate.Merge(m, src)
}
func (m *Candidate) XXX_Size() int {
	return xxx_messageInfo_Candidate.Size(m)
}
func (m *Candidate) XXX_DiscardUnknown() {
	xxx_messageInfo_Candidate.DiscardUnknown(m)
}

var xxx_messageInfo_Candidate proto.InternalMessageInfo

func (m *Candidate) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Candidate) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Candidate) GetTotalWeightedVotes() string {
	if m != nil {
		return m.TotalWeightedVotes
	}
	return ""
}

func (m *Candidate) GetSelfStakingTokens() string {
	if m != nil {
		return m.SelfStakingTokens
	}
	return ""
}

type GetCandidatesRequest struct {
	Height               string   `protobuf:"bytes,1,opt,name=height,proto3" json:"height,omitempty"`
	Offset               uint32   `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit                uint32   `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCandidatesRequest) Reset()         { *m = GetCandidatesRequest{} }
func (m *GetCandidatesRequest) String() string { return proto.CompactTextString(m) }
func (*GetCandidatesRequest) ProtoMessage()    {}
func (*GetCandidatesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_097e8f966f16a890, []int{3}
}

func (m *GetCandidatesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCandidatesRequest.Unmarshal(m, b)
}
func (m *GetCandidatesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCandidatesRequest.Marshal(b, m, deterministic)
}
func (m *GetCandidatesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCandidatesRequest.Merge(m, src)
}
func (m *GetCandidatesRequest) XXX_Size() int {
	return xxx_messageInfo_GetCandidatesRequest.Size(m)
}
func (m *GetCandidatesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCandidatesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetCandidatesRequest proto.InternalMessageInfo

func (m *GetCandidatesRequest) GetHeight() string {
	if m != nil {
		return m.Height
	}
	return ""
}

func (m *GetCandidatesRequest) GetOffset() uint32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *GetCandidatesRequest) GetLimit() uint32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type GetBucketsByCandidateRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Height               string   `protobuf:"bytes,2,opt,name=height,proto3" json:"height,omitempty"`
	Offset               uint32   `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit                uint32   `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBucketsByCandidateRequest) Reset()         { *m = GetBucketsByCandidateRequest{} }
func (m *GetBucketsByCandidateRequest) String() string { return proto.CompactTextString(m) }
func (*GetBucketsByCandidateRequest) ProtoMessage()    {}
func (*GetBucketsByCandidateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_097e8f966f16a890, []int{4}
}

func (m *GetBucketsByCandidateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBucketsByCandidateRequest.Unmarshal(m, b)
}
func (m *GetBucketsByCandidateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBucketsByCandidateRequest.Marshal(b, m, deterministic)
}
func (m *GetBucketsByCandidateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBucketsByCandidateRequest.Merge(m, src)
}
func (m *GetBucketsByCandidateRequest) XXX_Size() int {
	return xxx_messageInfo_GetBucketsByCandidateRequest.Size(m)
}
func (m *GetBucketsByCandidateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBucketsByCandidateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetBucketsByCandidateRequest proto.InternalMessageInfo

func (m *GetBucketsByCandidateRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GetBucketsByCandidateRequest) GetHeight() string {
	if m != nil {
		return m.Height
	}
	return ""
}

func (m *GetBucketsByCandidateRequest) GetOffset() uint32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *GetBucketsByCandidateRequest) GetLimit() uint32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type HealthCheckResponse struct {
	Status               HealthCheckResponse_Status `protobuf:"varint,1,opt,name=status,proto3,enum=ranking.HealthCheckResponse_Status" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *HealthCheckResponse) Reset()         { *m = HealthCheckResponse{} }
func (m *HealthCheckResponse) String() string { return proto.CompactTextString(m) }
func (*HealthCheckResponse) ProtoMessage()    {}
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_097e8f966f16a890, []int{5}
}

func (m *HealthCheckResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HealthCheckResponse.Unmarshal(m, b)
}
func (m *HealthCheckResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HealthCheckResponse.Marshal(b, m, deterministic)
}
func (m *HealthCheckResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HealthCheckResponse.Merge(m, src)
}
func (m *HealthCheckResponse) XXX_Size() int {
	return xxx_messageInfo_HealthCheckResponse.Size(m)
}
func (m *HealthCheckResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HealthCheckResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HealthCheckResponse proto.InternalMessageInfo

func (m *HealthCheckResponse) GetStatus() HealthCheckResponse_Status {
	if m != nil {
		return m.Status
	}
	return HealthCheckResponse_STARTING
}

type CandidateResponse struct {
	Candidates           []*Candidate `protobuf:"bytes,1,rep,name=candidates,proto3" json:"candidates,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *CandidateResponse) Reset()         { *m = CandidateResponse{} }
func (m *CandidateResponse) String() string { return proto.CompactTextString(m) }
func (*CandidateResponse) ProtoMessage()    {}
func (*CandidateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_097e8f966f16a890, []int{6}
}

func (m *CandidateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CandidateResponse.Unmarshal(m, b)
}
func (m *CandidateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CandidateResponse.Marshal(b, m, deterministic)
}
func (m *CandidateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CandidateResponse.Merge(m, src)
}
func (m *CandidateResponse) XXX_Size() int {
	return xxx_messageInfo_CandidateResponse.Size(m)
}
func (m *CandidateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CandidateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CandidateResponse proto.InternalMessageInfo

func (m *CandidateResponse) GetCandidates() []*Candidate {
	if m != nil {
		return m.Candidates
	}
	return nil
}

type BucketResponse struct {
	Buckets              []*Bucket `protobuf:"bytes,1,rep,name=buckets,proto3" json:"buckets,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *BucketResponse) Reset()         { *m = BucketResponse{} }
func (m *BucketResponse) String() string { return proto.CompactTextString(m) }
func (*BucketResponse) ProtoMessage()    {}
func (*BucketResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_097e8f966f16a890, []int{7}
}

func (m *BucketResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BucketResponse.Unmarshal(m, b)
}
func (m *BucketResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BucketResponse.Marshal(b, m, deterministic)
}
func (m *BucketResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BucketResponse.Merge(m, src)
}
func (m *BucketResponse) XXX_Size() int {
	return xxx_messageInfo_BucketResponse.Size(m)
}
func (m *BucketResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BucketResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BucketResponse proto.InternalMessageInfo

func (m *BucketResponse) GetBuckets() []*Bucket {
	if m != nil {
		return m.Buckets
	}
	return nil
}

func init() {
	proto.RegisterEnum("ranking.HealthCheckResponse_Status", HealthCheckResponse_Status_name, HealthCheckResponse_Status_value)
	proto.RegisterType((*ChainMeta)(nil), "ranking.ChainMeta")
	proto.RegisterType((*Bucket)(nil), "ranking.Bucket")
	proto.RegisterType((*Candidate)(nil), "ranking.Candidate")
	proto.RegisterType((*GetCandidatesRequest)(nil), "ranking.GetCandidatesRequest")
	proto.RegisterType((*GetBucketsByCandidateRequest)(nil), "ranking.GetBucketsByCandidateRequest")
	proto.RegisterType((*HealthCheckResponse)(nil), "ranking.HealthCheckResponse")
	proto.RegisterType((*CandidateResponse)(nil), "ranking.CandidateResponse")
	proto.RegisterType((*BucketResponse)(nil), "ranking.BucketResponse")
}

func init() { proto.RegisterFile("ranking.proto", fileDescriptor_097e8f966f16a890) }

var fileDescriptor_097e8f966f16a890 = []byte{
	// 572 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x53, 0x4f, 0x6f, 0xd3, 0x4e,
	0x10, 0x8d, 0xd3, 0xfc, 0x9c, 0x76, 0x7e, 0xa4, 0x7f, 0x86, 0x52, 0xa2, 0x50, 0x50, 0x64, 0x40,
	0x0a, 0x08, 0xb9, 0x28, 0x1c, 0x38, 0xf4, 0xd4, 0x84, 0x2a, 0x44, 0x82, 0x1e, 0x9c, 0xa8, 0x08,
	0x89, 0xcb, 0x26, 0x9e, 0x38, 0x56, 0x12, 0x6f, 0xf0, 0x6e, 0x80, 0xde, 0x39, 0xf0, 0x0d, 0x10,
	0x9f, 0x82, 0xaf, 0x88, 0xbc, 0xbb, 0x76, 0x4c, 0xe3, 0x70, 0xf3, 0xbc, 0x79, 0x9e, 0xf7, 0x66,
	0x76, 0x06, 0x6a, 0x31, 0x8b, 0x66, 0x61, 0x14, 0xb8, 0xcb, 0x98, 0x4b, 0x8e, 0x55, 0x13, 0x36,
	0x1e, 0x04, 0x9c, 0x07, 0x73, 0x3a, 0x53, 0xf0, 0x68, 0x35, 0x39, 0xa3, 0xc5, 0x52, 0xde, 0x68,
	0x96, 0xf3, 0xcb, 0x82, 0xbd, 0xee, 0x94, 0x85, 0xd1, 0x7b, 0x92, 0x0c, 0x4f, 0xc0, 0x9e, 0x52,
	0x18, 0x4c, 0x65, 0xdd, 0x6a, 0x5a, 0xad, 0x3d, 0xcf, 0x44, 0xd8, 0x82, 0x03, 0xc9, 0x25, 0x9b,
	0x77, 0x59, 0xe4, 0x87, 0x3e, 0x93, 0x24, 0xea, 0xe5, 0xa6, 0xd5, 0xaa, 0x78, 0xb7, 0x61, 0x7c,
	0x0e, 0x87, 0x0a, 0xba, 0xe6, 0x92, 0xfc, 0x81, 0x64, 0x33, 0x12, 0xf5, 0x1d, 0x55, 0x6b, 0x03,
	0xc7, 0x47, 0x00, 0x19, 0x26, 0xea, 0x15, 0xc5, 0xca, 0x21, 0xce, 0x0f, 0x0b, 0xec, 0xce, 0x6a,
	0x3c, 0x23, 0x89, 0xc7, 0xf0, 0xdf, 0x17, 0x2e, 0x29, 0x36, 0xbe, 0x74, 0x90, 0xa2, 0xda, 0x8c,
	0x41, 0x05, 0x3e, 0x81, 0xda, 0x57, 0x65, 0x9b, 0x7c, 0x5d, 0x59, 0xeb, 0xff, 0x0d, 0xe2, 0x0b,
	0x38, 0x8a, 0x69, 0xc1, 0xc2, 0x28, 0x8c, 0x82, 0x37, 0xab, 0x98, 0xc9, 0x90, 0x47, 0xc6, 0xc3,
	0x66, 0xc2, 0xf9, 0x99, 0x8c, 0x29, 0xed, 0x12, 0x11, 0x2a, 0x11, 0x5b, 0x90, 0x31, 0xa3, 0xbe,
	0xb1, 0x0e, 0x55, 0xe6, 0xfb, 0x31, 0x89, 0xd4, 0x4d, 0x1a, 0xa2, 0x0b, 0xa8, 0x9a, 0xfa, 0x50,
	0x60, 0xaa, 0x20, 0x93, 0x38, 0x1b, 0xd0, 0x7c, 0x92, 0x0c, 0x29, 0x8c, 0x82, 0x21, 0x9f, 0x51,
	0x94, 0x4e, 0x67, 0x33, 0xe1, 0x7c, 0x82, 0xe3, 0x1e, 0xc9, 0xf5, 0x0b, 0x78, 0xf4, 0x79, 0x45,
	0x42, 0x6e, 0x7d, 0xca, 0x13, 0xb0, 0xf9, 0x64, 0x22, 0x48, 0x2a, 0x9b, 0x35, 0xcf, 0x44, 0xc9,
	0x2c, 0xe7, 0xe1, 0x22, 0x94, 0xca, 0x58, 0xcd, 0xd3, 0x81, 0xf3, 0x0d, 0x4e, 0x7b, 0x24, 0xf5,
	0x23, 0x88, 0xce, 0x4d, 0x26, 0x93, 0xaa, 0x14, 0x4d, 0x62, 0xad, 0x5c, 0xde, 0xa2, 0xbc, 0x53,
	0xac, 0x5c, 0xc9, 0x2b, 0x7f, 0xb7, 0xe0, 0xee, 0x5b, 0x62, 0x73, 0x39, 0xed, 0x4e, 0x69, 0x3c,
	0xf3, 0x48, 0x2c, 0x79, 0x24, 0x08, 0xcf, 0xc1, 0x16, 0x92, 0xc9, 0x95, 0x50, 0x9a, 0xfb, 0xed,
	0xc7, 0x6e, 0xba, 0xf6, 0x05, 0x6c, 0x77, 0xa0, 0xa8, 0x9e, 0xf9, 0xc5, 0x79, 0x09, 0xb6, 0x46,
	0xf0, 0x0e, 0xec, 0x0e, 0x86, 0x17, 0xde, 0xb0, 0x7f, 0xd5, 0x3b, 0x2c, 0x21, 0x80, 0x7d, 0xd1,
	0x1d, 0xf6, 0xaf, 0x2f, 0x0f, 0xad, 0x24, 0xd3, 0xbf, 0x32, 0x51, 0xd9, 0xe9, 0xc1, 0x51, 0xae,
	0x69, 0xe3, 0xa1, 0x0d, 0x30, 0x5e, 0x5f, 0x82, 0xd5, 0xdc, 0x69, 0xfd, 0xdf, 0xc6, 0xcc, 0xc7,
	0x9a, 0x9f, 0x63, 0x39, 0xe7, 0xb0, 0xaf, 0xc7, 0x98, 0x55, 0x79, 0x06, 0xd5, 0x91, 0x1e, 0xac,
	0x29, 0x71, 0x90, 0x95, 0x30, 0xcc, 0x34, 0xdf, 0xfe, 0x5d, 0x86, 0xaa, 0xa7, 0x73, 0xf8, 0x1a,
	0xaa, 0x01, 0x49, 0x7d, 0xae, 0xae, 0x3e, 0x6d, 0x37, 0x3d, 0x6d, 0xf7, 0x32, 0x39, 0xed, 0x46,
	0xce, 0x4b, 0x7a, 0xda, 0x4e, 0x09, 0xdf, 0x41, 0x2d, 0xc8, 0x6f, 0x0a, 0x3e, 0xcc, 0x68, 0x45,
	0x1b, 0xd4, 0x68, 0x14, 0x74, 0x64, 0xbc, 0x3b, 0x25, 0xfc, 0x08, 0xf7, 0x82, 0xa2, 0xcd, 0xc0,
	0xa7, 0xf9, 0xaa, 0x5b, 0x37, 0xa7, 0x71, 0xff, 0x76, 0xb3, 0xeb, 0xd2, 0x1d, 0xd8, 0x0d, 0x85,
	0x7e, 0xcd, 0xad, 0x2d, 0x9e, 0xfe, 0xeb, 0xd9, 0x9d, 0xd2, 0xc8, 0x56, 0xfc, 0x57, 0x7f, 0x02,
	0x00, 0x00, 0xff, 0xff, 0xa8, 0x55, 0xf9, 0x82, 0x15, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RankingClient is the client API for Ranking service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RankingClient interface {
	// get the blockchain meta data
	GetMeta(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*ChainMeta, error)
	// get candidates
	GetCandidates(ctx context.Context, in *GetCandidatesRequest, opts ...grpc.CallOption) (*CandidateResponse, error)
	// get buckets by candidate
	GetBucketsByCandidate(ctx context.Context, in *GetBucketsByCandidateRequest, opts ...grpc.CallOption) (*BucketResponse, error)
	// health endpoint
	IsHealth(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*HealthCheckResponse, error)
}

type rankingClient struct {
	cc *grpc.ClientConn
}

func NewRankingClient(cc *grpc.ClientConn) RankingClient {
	return &rankingClient{cc}
}

func (c *rankingClient) GetMeta(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*ChainMeta, error) {
	out := new(ChainMeta)
	err := c.cc.Invoke(ctx, "/ranking.Ranking/getMeta", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rankingClient) GetCandidates(ctx context.Context, in *GetCandidatesRequest, opts ...grpc.CallOption) (*CandidateResponse, error) {
	out := new(CandidateResponse)
	err := c.cc.Invoke(ctx, "/ranking.Ranking/getCandidates", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rankingClient) GetBucketsByCandidate(ctx context.Context, in *GetBucketsByCandidateRequest, opts ...grpc.CallOption) (*BucketResponse, error) {
	out := new(BucketResponse)
	err := c.cc.Invoke(ctx, "/ranking.Ranking/getBucketsByCandidate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rankingClient) IsHealth(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, "/ranking.Ranking/isHealth", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RankingServer is the server API for Ranking service.
type RankingServer interface {
	// get the blockchain meta data
	GetMeta(context.Context, *empty.Empty) (*ChainMeta, error)
	// get candidates
	GetCandidates(context.Context, *GetCandidatesRequest) (*CandidateResponse, error)
	// get buckets by candidate
	GetBucketsByCandidate(context.Context, *GetBucketsByCandidateRequest) (*BucketResponse, error)
	// health endpoint
	IsHealth(context.Context, *empty.Empty) (*HealthCheckResponse, error)
}

func RegisterRankingServer(s *grpc.Server, srv RankingServer) {
	s.RegisterService(&_Ranking_serviceDesc, srv)
}

func _Ranking_GetMeta_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RankingServer).GetMeta(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ranking.Ranking/GetMeta",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RankingServer).GetMeta(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ranking_GetCandidates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCandidatesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RankingServer).GetCandidates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ranking.Ranking/GetCandidates",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RankingServer).GetCandidates(ctx, req.(*GetCandidatesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ranking_GetBucketsByCandidate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBucketsByCandidateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RankingServer).GetBucketsByCandidate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ranking.Ranking/GetBucketsByCandidate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RankingServer).GetBucketsByCandidate(ctx, req.(*GetBucketsByCandidateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ranking_IsHealth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RankingServer).IsHealth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ranking.Ranking/IsHealth",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RankingServer).IsHealth(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _Ranking_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ranking.Ranking",
	HandlerType: (*RankingServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "getMeta",
			Handler:    _Ranking_GetMeta_Handler,
		},
		{
			MethodName: "getCandidates",
			Handler:    _Ranking_GetCandidates_Handler,
		},
		{
			MethodName: "getBucketsByCandidate",
			Handler:    _Ranking_GetBucketsByCandidate_Handler,
		},
		{
			MethodName: "isHealth",
			Handler:    _Ranking_IsHealth_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ranking.proto",
}
