// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/election/election.proto

package election

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	duration "github.com/golang/protobuf/ptypes/duration"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Bucket struct {
	Voter                []byte               `protobuf:"bytes,1,opt,name=voter,proto3" json:"voter,omitempty"`
	Candidate            []byte               `protobuf:"bytes,2,opt,name=candidate,proto3" json:"candidate,omitempty"`
	Amount               []byte               `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`
	StartTime            *timestamp.Timestamp `protobuf:"bytes,4,opt,name=startTime,proto3" json:"startTime,omitempty"`
	Duration             *duration.Duration   `protobuf:"bytes,5,opt,name=duration,proto3" json:"duration,omitempty"`
	Decay                bool                 `protobuf:"varint,6,opt,name=decay,proto3" json:"decay,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Bucket) Reset()         { *m = Bucket{} }
func (m *Bucket) String() string { return proto.CompactTextString(m) }
func (*Bucket) ProtoMessage()    {}
func (*Bucket) Descriptor() ([]byte, []int) {
	return fileDescriptor_14eaa3cbe7662e2a, []int{0}
}

func (m *Bucket) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Bucket.Unmarshal(m, b)
}
func (m *Bucket) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Bucket.Marshal(b, m, deterministic)
}
func (m *Bucket) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Bucket.Merge(m, src)
}
func (m *Bucket) XXX_Size() int {
	return xxx_messageInfo_Bucket.Size(m)
}
func (m *Bucket) XXX_DiscardUnknown() {
	xxx_messageInfo_Bucket.DiscardUnknown(m)
}

var xxx_messageInfo_Bucket proto.InternalMessageInfo

func (m *Bucket) GetVoter() []byte {
	if m != nil {
		return m.Voter
	}
	return nil
}

func (m *Bucket) GetCandidate() []byte {
	if m != nil {
		return m.Candidate
	}
	return nil
}

func (m *Bucket) GetAmount() []byte {
	if m != nil {
		return m.Amount
	}
	return nil
}

func (m *Bucket) GetStartTime() *timestamp.Timestamp {
	if m != nil {
		return m.StartTime
	}
	return nil
}

func (m *Bucket) GetDuration() *duration.Duration {
	if m != nil {
		return m.Duration
	}
	return nil
}

func (m *Bucket) GetDecay() bool {
	if m != nil {
		return m.Decay
	}
	return false
}

type Registration struct {
	Name                 []byte   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Address              []byte   `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	OperatorAddress      []byte   `protobuf:"bytes,3,opt,name=operatorAddress,proto3" json:"operatorAddress,omitempty"`
	RewardAddress        []byte   `protobuf:"bytes,4,opt,name=rewardAddress,proto3" json:"rewardAddress,omitempty"`
	SelfStakingWeight    uint64   `protobuf:"varint,5,opt,name=selfStakingWeight,proto3" json:"selfStakingWeight,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Registration) Reset()         { *m = Registration{} }
func (m *Registration) String() string { return proto.CompactTextString(m) }
func (*Registration) ProtoMessage()    {}
func (*Registration) Descriptor() ([]byte, []int) {
	return fileDescriptor_14eaa3cbe7662e2a, []int{1}
}

func (m *Registration) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Registration.Unmarshal(m, b)
}
func (m *Registration) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Registration.Marshal(b, m, deterministic)
}
func (m *Registration) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Registration.Merge(m, src)
}
func (m *Registration) XXX_Size() int {
	return xxx_messageInfo_Registration.Size(m)
}
func (m *Registration) XXX_DiscardUnknown() {
	xxx_messageInfo_Registration.DiscardUnknown(m)
}

var xxx_messageInfo_Registration proto.InternalMessageInfo

func (m *Registration) GetName() []byte {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *Registration) GetAddress() []byte {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *Registration) GetOperatorAddress() []byte {
	if m != nil {
		return m.OperatorAddress
	}
	return nil
}

func (m *Registration) GetRewardAddress() []byte {
	if m != nil {
		return m.RewardAddress
	}
	return nil
}

func (m *Registration) GetSelfStakingWeight() uint64 {
	if m != nil {
		return m.SelfStakingWeight
	}
	return 0
}

type Poll struct {
	Registrations        [][]byte `protobuf:"bytes,1,rep,name=registrations,proto3" json:"registrations,omitempty"`
	Buckets              [][]byte `protobuf:"bytes,2,rep,name=buckets,proto3" json:"buckets,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Poll) Reset()         { *m = Poll{} }
func (m *Poll) String() string { return proto.CompactTextString(m) }
func (*Poll) ProtoMessage()    {}
func (*Poll) Descriptor() ([]byte, []int) {
	return fileDescriptor_14eaa3cbe7662e2a, []int{2}
}

func (m *Poll) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Poll.Unmarshal(m, b)
}
func (m *Poll) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Poll.Marshal(b, m, deterministic)
}
func (m *Poll) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Poll.Merge(m, src)
}
func (m *Poll) XXX_Size() int {
	return xxx_messageInfo_Poll.Size(m)
}
func (m *Poll) XXX_DiscardUnknown() {
	xxx_messageInfo_Poll.DiscardUnknown(m)
}

var xxx_messageInfo_Poll proto.InternalMessageInfo

func (m *Poll) GetRegistrations() [][]byte {
	if m != nil {
		return m.Registrations
	}
	return nil
}

func (m *Poll) GetBuckets() [][]byte {
	if m != nil {
		return m.Buckets
	}
	return nil
}

type Vote struct {
	Voter                []byte               `protobuf:"bytes,1,opt,name=voter,proto3" json:"voter,omitempty"`
	Candidate            []byte               `protobuf:"bytes,2,opt,name=candidate,proto3" json:"candidate,omitempty"`
	Amount               []byte               `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`
	WeightedAmount       []byte               `protobuf:"bytes,4,opt,name=weightedAmount,proto3" json:"weightedAmount,omitempty"`
	StartTime            *timestamp.Timestamp `protobuf:"bytes,5,opt,name=startTime,proto3" json:"startTime,omitempty"`
	Duration             *duration.Duration   `protobuf:"bytes,6,opt,name=duration,proto3" json:"duration,omitempty"`
	Decay                bool                 `protobuf:"varint,7,opt,name=decay,proto3" json:"decay,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Vote) Reset()         { *m = Vote{} }
func (m *Vote) String() string { return proto.CompactTextString(m) }
func (*Vote) ProtoMessage()    {}
func (*Vote) Descriptor() ([]byte, []int) {
	return fileDescriptor_14eaa3cbe7662e2a, []int{3}
}

func (m *Vote) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Vote.Unmarshal(m, b)
}
func (m *Vote) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Vote.Marshal(b, m, deterministic)
}
func (m *Vote) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Vote.Merge(m, src)
}
func (m *Vote) XXX_Size() int {
	return xxx_messageInfo_Vote.Size(m)
}
func (m *Vote) XXX_DiscardUnknown() {
	xxx_messageInfo_Vote.DiscardUnknown(m)
}

var xxx_messageInfo_Vote proto.InternalMessageInfo

func (m *Vote) GetVoter() []byte {
	if m != nil {
		return m.Voter
	}
	return nil
}

func (m *Vote) GetCandidate() []byte {
	if m != nil {
		return m.Candidate
	}
	return nil
}

func (m *Vote) GetAmount() []byte {
	if m != nil {
		return m.Amount
	}
	return nil
}

func (m *Vote) GetWeightedAmount() []byte {
	if m != nil {
		return m.WeightedAmount
	}
	return nil
}

func (m *Vote) GetStartTime() *timestamp.Timestamp {
	if m != nil {
		return m.StartTime
	}
	return nil
}

func (m *Vote) GetDuration() *duration.Duration {
	if m != nil {
		return m.Duration
	}
	return nil
}

func (m *Vote) GetDecay() bool {
	if m != nil {
		return m.Decay
	}
	return false
}

type VoteList struct {
	Votes                []*Vote  `protobuf:"bytes,1,rep,name=votes,proto3" json:"votes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VoteList) Reset()         { *m = VoteList{} }
func (m *VoteList) String() string { return proto.CompactTextString(m) }
func (*VoteList) ProtoMessage()    {}
func (*VoteList) Descriptor() ([]byte, []int) {
	return fileDescriptor_14eaa3cbe7662e2a, []int{4}
}

func (m *VoteList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VoteList.Unmarshal(m, b)
}
func (m *VoteList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VoteList.Marshal(b, m, deterministic)
}
func (m *VoteList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VoteList.Merge(m, src)
}
func (m *VoteList) XXX_Size() int {
	return xxx_messageInfo_VoteList.Size(m)
}
func (m *VoteList) XXX_DiscardUnknown() {
	xxx_messageInfo_VoteList.DiscardUnknown(m)
}

var xxx_messageInfo_VoteList proto.InternalMessageInfo

func (m *VoteList) GetVotes() []*Vote {
	if m != nil {
		return m.Votes
	}
	return nil
}

type Candidate struct {
	Name                 []byte   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Address              []byte   `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	OperatorAddress      []byte   `protobuf:"bytes,3,opt,name=operatorAddress,proto3" json:"operatorAddress,omitempty"`
	RewardAddress        []byte   `protobuf:"bytes,4,opt,name=rewardAddress,proto3" json:"rewardAddress,omitempty"`
	SelfStakingWeight    uint64   `protobuf:"varint,5,opt,name=selfStakingWeight,proto3" json:"selfStakingWeight,omitempty"`
	Score                []byte   `protobuf:"bytes,6,opt,name=score,proto3" json:"score,omitempty"`
	SelfStakingTokens    []byte   `protobuf:"bytes,7,opt,name=selfStakingTokens,proto3" json:"selfStakingTokens,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Candidate) Reset()         { *m = Candidate{} }
func (m *Candidate) String() string { return proto.CompactTextString(m) }
func (*Candidate) ProtoMessage()    {}
func (*Candidate) Descriptor() ([]byte, []int) {
	return fileDescriptor_14eaa3cbe7662e2a, []int{5}
}

func (m *Candidate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Candidate.Unmarshal(m, b)
}
func (m *Candidate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Candidate.Marshal(b, m, deterministic)
}
func (m *Candidate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Candidate.Merge(m, src)
}
func (m *Candidate) XXX_Size() int {
	return xxx_messageInfo_Candidate.Size(m)
}
func (m *Candidate) XXX_DiscardUnknown() {
	xxx_messageInfo_Candidate.DiscardUnknown(m)
}

var xxx_messageInfo_Candidate proto.InternalMessageInfo

func (m *Candidate) GetName() []byte {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *Candidate) GetAddress() []byte {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *Candidate) GetOperatorAddress() []byte {
	if m != nil {
		return m.OperatorAddress
	}
	return nil
}

func (m *Candidate) GetRewardAddress() []byte {
	if m != nil {
		return m.RewardAddress
	}
	return nil
}

func (m *Candidate) GetSelfStakingWeight() uint64 {
	if m != nil {
		return m.SelfStakingWeight
	}
	return 0
}

func (m *Candidate) GetScore() []byte {
	if m != nil {
		return m.Score
	}
	return nil
}

func (m *Candidate) GetSelfStakingTokens() []byte {
	if m != nil {
		return m.SelfStakingTokens
	}
	return nil
}

type ElectionResult struct {
	Timestamp            *timestamp.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Delegates            []*Candidate         `protobuf:"bytes,2,rep,name=delegates,proto3" json:"delegates,omitempty"`
	DelegateVotes        []*VoteList          `protobuf:"bytes,3,rep,name=delegateVotes,proto3" json:"delegateVotes,omitempty"`
	TotalVotedStakes     []byte               `protobuf:"bytes,4,opt,name=totalVotedStakes,proto3" json:"totalVotedStakes,omitempty"`
	TotalVotes           []byte               `protobuf:"bytes,5,opt,name=totalVotes,proto3" json:"totalVotes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ElectionResult) Reset()         { *m = ElectionResult{} }
func (m *ElectionResult) String() string { return proto.CompactTextString(m) }
func (*ElectionResult) ProtoMessage()    {}
func (*ElectionResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_14eaa3cbe7662e2a, []int{6}
}

func (m *ElectionResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ElectionResult.Unmarshal(m, b)
}
func (m *ElectionResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ElectionResult.Marshal(b, m, deterministic)
}
func (m *ElectionResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ElectionResult.Merge(m, src)
}
func (m *ElectionResult) XXX_Size() int {
	return xxx_messageInfo_ElectionResult.Size(m)
}
func (m *ElectionResult) XXX_DiscardUnknown() {
	xxx_messageInfo_ElectionResult.DiscardUnknown(m)
}

var xxx_messageInfo_ElectionResult proto.InternalMessageInfo

func (m *ElectionResult) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *ElectionResult) GetDelegates() []*Candidate {
	if m != nil {
		return m.Delegates
	}
	return nil
}

func (m *ElectionResult) GetDelegateVotes() []*VoteList {
	if m != nil {
		return m.DelegateVotes
	}
	return nil
}

func (m *ElectionResult) GetTotalVotedStakes() []byte {
	if m != nil {
		return m.TotalVotedStakes
	}
	return nil
}

func (m *ElectionResult) GetTotalVotes() []byte {
	if m != nil {
		return m.TotalVotes
	}
	return nil
}

func init() {
	proto.RegisterType((*Bucket)(nil), "election.Bucket")
	proto.RegisterType((*Registration)(nil), "election.Registration")
	proto.RegisterType((*Poll)(nil), "election.Poll")
	proto.RegisterType((*Vote)(nil), "election.Vote")
	proto.RegisterType((*VoteList)(nil), "election.VoteList")
	proto.RegisterType((*Candidate)(nil), "election.Candidate")
	proto.RegisterType((*ElectionResult)(nil), "election.ElectionResult")
}

func init() { proto.RegisterFile("pb/election/election.proto", fileDescriptor_14eaa3cbe7662e2a) }

var fileDescriptor_14eaa3cbe7662e2a = []byte{
	// 555 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x54, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0x95, 0x53, 0x27, 0x4d, 0xa6, 0x69, 0x80, 0x05, 0x21, 0x13, 0xa1, 0x12, 0x59, 0x15, 0x8a,
	0x10, 0x38, 0x10, 0x40, 0xea, 0xb5, 0xe5, 0xe3, 0xc4, 0x01, 0x2d, 0x51, 0x91, 0xb8, 0x6d, 0xec,
	0xa9, 0x6b, 0x62, 0x7b, 0xad, 0xdd, 0x35, 0x85, 0x23, 0xe2, 0x5f, 0xf1, 0x57, 0xf8, 0x29, 0x5c,
	0xd0, 0xee, 0xfa, 0x23, 0x1f, 0x07, 0xa4, 0x8a, 0x0b, 0x37, 0xbf, 0x37, 0x6f, 0x57, 0xf3, 0xde,
	0x8c, 0x17, 0xc6, 0xc5, 0x72, 0x86, 0x29, 0x86, 0x2a, 0xe1, 0x79, 0xf3, 0x11, 0x14, 0x82, 0x2b,
	0x4e, 0xfa, 0x35, 0x1e, 0x1f, 0xc5, 0x9c, 0xc7, 0x29, 0xce, 0x0c, 0xbf, 0x2c, 0x2f, 0x66, 0x51,
	0x29, 0x58, 0xab, 0x1c, 0x3f, 0xd8, 0xae, 0xab, 0x24, 0x43, 0xa9, 0x58, 0x56, 0x58, 0x81, 0xff,
	0xcb, 0x81, 0xde, 0x59, 0x19, 0xae, 0x50, 0x91, 0x3b, 0xd0, 0xfd, 0xc2, 0x15, 0x0a, 0xcf, 0x99,
	0x38, 0xd3, 0x21, 0xb5, 0x80, 0xdc, 0x87, 0x41, 0xc8, 0xf2, 0x28, 0x89, 0x98, 0x42, 0xaf, 0x63,
	0x2a, 0x2d, 0x41, 0xee, 0x42, 0x8f, 0x65, 0xbc, 0xcc, 0x95, 0xb7, 0x67, 0x4a, 0x15, 0x22, 0x27,
	0x30, 0x90, 0x8a, 0x09, 0xb5, 0x48, 0x32, 0xf4, 0xdc, 0x89, 0x33, 0x3d, 0x98, 0x8f, 0x03, 0xdb,
	0x4b, 0x50, 0xf7, 0x12, 0x2c, 0xea, 0x5e, 0x68, 0x2b, 0x26, 0x2f, 0xa1, 0x5f, 0x7b, 0xf0, 0xba,
	0xe6, 0xe0, 0xbd, 0x9d, 0x83, 0xaf, 0x2b, 0x01, 0x6d, 0xa4, 0xba, 0xf9, 0x08, 0x43, 0xf6, 0xcd,
	0xeb, 0x4d, 0x9c, 0x69, 0x9f, 0x5a, 0xe0, 0xff, 0x74, 0x60, 0x48, 0x31, 0x4e, 0xa4, 0xaa, 0x64,
	0x04, 0xdc, 0x9c, 0x65, 0x58, 0x59, 0x34, 0xdf, 0xc4, 0x83, 0x7d, 0x16, 0x45, 0x02, 0xa5, 0xac,
	0xfc, 0xd5, 0x90, 0x4c, 0xe1, 0x06, 0x2f, 0x50, 0x30, 0xc5, 0xc5, 0x69, 0xa5, 0xb0, 0x36, 0xb7,
	0x69, 0x72, 0x0c, 0x87, 0x02, 0xaf, 0x98, 0x88, 0x6a, 0x9d, 0x6b, 0x74, 0x9b, 0x24, 0x79, 0x0c,
	0xb7, 0x24, 0xa6, 0x17, 0x1f, 0x14, 0x5b, 0x25, 0x79, 0xfc, 0x11, 0x93, 0xf8, 0x52, 0x19, 0x93,
	0x2e, 0xdd, 0x2d, 0xf8, 0x6f, 0xc1, 0x7d, 0xcf, 0xd3, 0xd4, 0xde, 0xdd, 0x7a, 0x90, 0x9e, 0x33,
	0xd9, 0xb3, 0x77, 0xaf, 0x91, 0xda, 0xc5, 0xd2, 0xcc, 0x51, 0xbb, 0xd0, 0xf5, 0x1a, 0xfa, 0xdf,
	0x3b, 0xe0, 0x9e, 0x73, 0x85, 0xff, 0x74, 0xc0, 0x0f, 0x61, 0x74, 0x65, 0xda, 0xc4, 0xe8, 0xd4,
	0xd6, 0xad, 0xe3, 0x2d, 0x76, 0x73, 0x11, 0xba, 0xd7, 0x5d, 0x84, 0xde, 0x35, 0x16, 0x61, 0x7f,
	0x7d, 0x11, 0x9e, 0x42, 0x5f, 0x47, 0xf0, 0x2e, 0x91, 0x8a, 0x1c, 0xdb, 0x18, 0x6c, 0x8e, 0x07,
	0xf3, 0x51, 0xd0, 0xfc, 0x5d, 0x5a, 0x62, 0x63, 0x91, 0xfe, 0x6f, 0x07, 0x06, 0xaf, 0x9a, 0x18,
	0xfe, 0xa3, 0xbd, 0xd1, 0x09, 0xc8, 0x90, 0x0b, 0x34, 0xa9, 0x0d, 0xa9, 0x05, 0x5b, 0x77, 0x2c,
	0xf8, 0x0a, 0x73, 0x69, 0x32, 0x1a, 0xd2, 0xdd, 0x82, 0xff, 0xa3, 0x03, 0xa3, 0x37, 0x55, 0x2c,
	0x14, 0x65, 0x99, 0x9a, 0x49, 0x36, 0x8f, 0x87, 0xc9, 0xe1, 0x2f, 0x93, 0x6c, 0xc4, 0xe4, 0x19,
	0x0c, 0x22, 0x4c, 0x31, 0x66, 0x3a, 0xf4, 0x8e, 0x09, 0xfd, 0x76, 0x1b, 0x7a, 0x13, 0x32, 0x6d,
	0x55, 0xe4, 0x04, 0x0e, 0x6b, 0x70, 0x6e, 0x66, 0xb5, 0x67, 0x8e, 0x91, 0xcd, 0x59, 0xe9, 0x71,
	0xd2, 0x4d, 0x21, 0x79, 0x04, 0x37, 0x15, 0x57, 0x2c, 0xd5, 0x28, 0xd2, 0xa6, 0xb0, 0x0e, 0x75,
	0x87, 0x27, 0x47, 0x00, 0x0d, 0x27, 0x4d, 0xa0, 0x43, 0xba, 0xc6, 0x9c, 0xbd, 0xf8, 0x34, 0x8f,
	0x13, 0x75, 0x59, 0x2e, 0x83, 0x90, 0x67, 0xb3, 0x84, 0x2b, 0xfc, 0x5a, 0x08, 0xfe, 0x19, 0x43,
	0x65, 0xc1, 0x93, 0xe6, 0x81, 0x5e, 0x7b, 0xac, 0x97, 0x3d, 0x93, 0xc6, 0xf3, 0x3f, 0x01, 0x00,
	0x00, 0xff, 0xff, 0x82, 0x3d, 0xa6, 0x78, 0xc2, 0x05, 0x00, 0x00,
}
