// Code generated by protoc-gen-go. DO NOT EDIT.
// source: election.proto

package election

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	duration "github.com/golang/protobuf/ptypes/duration"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Vote struct {
	Voter                []byte               `protobuf:"bytes,1,opt,name=voter,proto3" json:"voter,omitempty"`
	Candidate            []byte               `protobuf:"bytes,2,opt,name=candidate,proto3" json:"candidate,omitempty"`
	Amount               []byte               `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`
	WeightedAmount       []byte               `protobuf:"bytes,4,opt,name=weightedAmount,proto3" json:"weightedAmount,omitempty"`
	StartTime            *timestamp.Timestamp `protobuf:"bytes,5,opt,name=startTime,proto3" json:"startTime,omitempty"`
	Duration             *duration.Duration   `protobuf:"bytes,6,opt,name=duration,proto3" json:"duration,omitempty"`
	Decay                bool                 `protobuf:"varint,7,opt,name=decay,proto3" json:"decay,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Vote) Reset()         { *m = Vote{} }
func (m *Vote) String() string { return proto.CompactTextString(m) }
func (*Vote) ProtoMessage()    {}
func (*Vote) Descriptor() ([]byte, []int) {
	return fileDescriptor_64dbf621b3c93457, []int{0}
}

func (m *Vote) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Vote.Unmarshal(m, b)
}
func (m *Vote) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Vote.Marshal(b, m, deterministic)
}
func (m *Vote) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Vote.Merge(m, src)
}
func (m *Vote) XXX_Size() int {
	return xxx_messageInfo_Vote.Size(m)
}
func (m *Vote) XXX_DiscardUnknown() {
	xxx_messageInfo_Vote.DiscardUnknown(m)
}

var xxx_messageInfo_Vote proto.InternalMessageInfo

func (m *Vote) GetVoter() []byte {
	if m != nil {
		return m.Voter
	}
	return nil
}

func (m *Vote) GetCandidate() []byte {
	if m != nil {
		return m.Candidate
	}
	return nil
}

func (m *Vote) GetAmount() []byte {
	if m != nil {
		return m.Amount
	}
	return nil
}

func (m *Vote) GetWeightedAmount() []byte {
	if m != nil {
		return m.WeightedAmount
	}
	return nil
}

func (m *Vote) GetStartTime() *timestamp.Timestamp {
	if m != nil {
		return m.StartTime
	}
	return nil
}

func (m *Vote) GetDuration() *duration.Duration {
	if m != nil {
		return m.Duration
	}
	return nil
}

func (m *Vote) GetDecay() bool {
	if m != nil {
		return m.Decay
	}
	return false
}

type VoteList struct {
	Votes                []*Vote  `protobuf:"bytes,1,rep,name=votes,proto3" json:"votes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VoteList) Reset()         { *m = VoteList{} }
func (m *VoteList) String() string { return proto.CompactTextString(m) }
func (*VoteList) ProtoMessage()    {}
func (*VoteList) Descriptor() ([]byte, []int) {
	return fileDescriptor_64dbf621b3c93457, []int{1}
}

func (m *VoteList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VoteList.Unmarshal(m, b)
}
func (m *VoteList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VoteList.Marshal(b, m, deterministic)
}
func (m *VoteList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VoteList.Merge(m, src)
}
func (m *VoteList) XXX_Size() int {
	return xxx_messageInfo_VoteList.Size(m)
}
func (m *VoteList) XXX_DiscardUnknown() {
	xxx_messageInfo_VoteList.DiscardUnknown(m)
}

var xxx_messageInfo_VoteList proto.InternalMessageInfo

func (m *VoteList) GetVotes() []*Vote {
	if m != nil {
		return m.Votes
	}
	return nil
}

type Candidate struct {
	Name                 []byte   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Address              []byte   `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	OperatorPubKey       []byte   `protobuf:"bytes,3,opt,name=operatorPubKey,proto3" json:"operatorPubKey,omitempty"`
	RewardPubKey         []byte   `protobuf:"bytes,4,opt,name=rewardPubKey,proto3" json:"rewardPubKey,omitempty"`
	SelfStakingWeight    uint32   `protobuf:"varint,5,opt,name=selfStakingWeight,proto3" json:"selfStakingWeight,omitempty"`
	Score                []byte   `protobuf:"bytes,6,opt,name=score,proto3" json:"score,omitempty"`
	SelfStakingScore     []byte   `protobuf:"bytes,7,opt,name=selfStakingScore,proto3" json:"selfStakingScore,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Candidate) Reset()         { *m = Candidate{} }
func (m *Candidate) String() string { return proto.CompactTextString(m) }
func (*Candidate) ProtoMessage()    {}
func (*Candidate) Descriptor() ([]byte, []int) {
	return fileDescriptor_64dbf621b3c93457, []int{2}
}

func (m *Candidate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Candidate.Unmarshal(m, b)
}
func (m *Candidate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Candidate.Marshal(b, m, deterministic)
}
func (m *Candidate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Candidate.Merge(m, src)
}
func (m *Candidate) XXX_Size() int {
	return xxx_messageInfo_Candidate.Size(m)
}
func (m *Candidate) XXX_DiscardUnknown() {
	xxx_messageInfo_Candidate.DiscardUnknown(m)
}

var xxx_messageInfo_Candidate proto.InternalMessageInfo

func (m *Candidate) GetName() []byte {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *Candidate) GetAddress() []byte {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *Candidate) GetOperatorPubKey() []byte {
	if m != nil {
		return m.OperatorPubKey
	}
	return nil
}

func (m *Candidate) GetRewardPubKey() []byte {
	if m != nil {
		return m.RewardPubKey
	}
	return nil
}

func (m *Candidate) GetSelfStakingWeight() uint32 {
	if m != nil {
		return m.SelfStakingWeight
	}
	return 0
}

func (m *Candidate) GetScore() []byte {
	if m != nil {
		return m.Score
	}
	return nil
}

func (m *Candidate) GetSelfStakingScore() []byte {
	if m != nil {
		return m.SelfStakingScore
	}
	return nil
}

type ElectionResult struct {
	Timestamp            *timestamp.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Delegates            []*Candidate         `protobuf:"bytes,2,rep,name=delegates,proto3" json:"delegates,omitempty"`
	DelegateVotes        []*VoteList          `protobuf:"bytes,3,rep,name=delegateVotes,proto3" json:"delegateVotes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ElectionResult) Reset()         { *m = ElectionResult{} }
func (m *ElectionResult) String() string { return proto.CompactTextString(m) }
func (*ElectionResult) ProtoMessage()    {}
func (*ElectionResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_64dbf621b3c93457, []int{3}
}

func (m *ElectionResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ElectionResult.Unmarshal(m, b)
}
func (m *ElectionResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ElectionResult.Marshal(b, m, deterministic)
}
func (m *ElectionResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ElectionResult.Merge(m, src)
}
func (m *ElectionResult) XXX_Size() int {
	return xxx_messageInfo_ElectionResult.Size(m)
}
func (m *ElectionResult) XXX_DiscardUnknown() {
	xxx_messageInfo_ElectionResult.DiscardUnknown(m)
}

var xxx_messageInfo_ElectionResult proto.InternalMessageInfo

func (m *ElectionResult) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *ElectionResult) GetDelegates() []*Candidate {
	if m != nil {
		return m.Delegates
	}
	return nil
}

func (m *ElectionResult) GetDelegateVotes() []*VoteList {
	if m != nil {
		return m.DelegateVotes
	}
	return nil
}

func init() {
	proto.RegisterType((*Vote)(nil), "election.Vote")
	proto.RegisterType((*VoteList)(nil), "election.VoteList")
	proto.RegisterType((*Candidate)(nil), "election.Candidate")
	proto.RegisterType((*ElectionResult)(nil), "election.ElectionResult")
}

func init() { proto.RegisterFile("election.proto", fileDescriptor_64dbf621b3c93457) }

var fileDescriptor_64dbf621b3c93457 = []byte{
	// 426 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0x86, 0xe5, 0x24, 0xcd, 0xc7, 0x34, 0x8d, 0x60, 0x40, 0xc8, 0x44, 0x08, 0x22, 0x0b, 0xa1,
	0x08, 0x21, 0x17, 0x8a, 0x90, 0x7a, 0x45, 0xc0, 0x09, 0x0e, 0x68, 0x5b, 0x95, 0xf3, 0xc6, 0x3b,
	0x35, 0x16, 0xb6, 0x37, 0xda, 0x5d, 0x53, 0xe5, 0xc8, 0xaf, 0xe2, 0x97, 0x71, 0x47, 0x9e, 0xf5,
	0x07, 0x49, 0x0e, 0xdc, 0xfc, 0xce, 0x3c, 0x2b, 0xcd, 0x3c, 0x63, 0x58, 0x50, 0x4e, 0x89, 0xcb,
	0x74, 0x19, 0x6f, 0x8d, 0x76, 0x1a, 0xa7, 0x6d, 0x5e, 0x3e, 0x4d, 0xb5, 0x4e, 0x73, 0x3a, 0xe7,
	0xfa, 0xa6, 0xba, 0x3d, 0x57, 0x95, 0x91, 0x3d, 0xb9, 0x7c, 0x76, 0xd8, 0x77, 0x59, 0x41, 0xd6,
	0xc9, 0x62, 0xeb, 0x81, 0xe8, 0xd7, 0x00, 0x46, 0x37, 0xda, 0x11, 0x3e, 0x84, 0x93, 0x9f, 0xda,
	0x91, 0x09, 0x83, 0x55, 0xb0, 0x9e, 0x0b, 0x1f, 0xf0, 0x09, 0xcc, 0x12, 0x59, 0xaa, 0x4c, 0x49,
	0x47, 0xe1, 0x80, 0x3b, 0x7d, 0x01, 0x1f, 0xc1, 0x58, 0x16, 0xba, 0x2a, 0x5d, 0x38, 0xe4, 0x56,
	0x93, 0xf0, 0x05, 0x2c, 0xee, 0x28, 0x4b, 0xbf, 0x3b, 0x52, 0xef, 0x7d, 0x7f, 0xc4, 0xfd, 0x83,
	0x2a, 0x5e, 0xc2, 0xcc, 0x3a, 0x69, 0xdc, 0x75, 0x56, 0x50, 0x78, 0xb2, 0x0a, 0xd6, 0xa7, 0x17,
	0xcb, 0xd8, 0x4f, 0x1c, 0xb7, 0x13, 0xc7, 0xd7, 0xed, 0xc4, 0xa2, 0x87, 0xf1, 0x1d, 0x4c, 0xdb,
	0x4d, 0xc3, 0x31, 0x3f, 0x7c, 0x7c, 0xf4, 0xf0, 0x63, 0x03, 0x88, 0x0e, 0xad, 0x97, 0x54, 0x94,
	0xc8, 0x5d, 0x38, 0x59, 0x05, 0xeb, 0xa9, 0xf0, 0x21, 0x7a, 0x0d, 0xd3, 0x5a, 0xc1, 0x97, 0xcc,
	0x3a, 0x7c, 0xee, 0x35, 0xd8, 0x30, 0x58, 0x0d, 0xd7, 0xa7, 0x17, 0x8b, 0xb8, 0x53, 0x5f, 0x23,
	0x5e, 0x8b, 0x8d, 0xfe, 0x04, 0x30, 0xfb, 0xd0, 0x69, 0x40, 0x18, 0x95, 0xb2, 0xa0, 0xc6, 0x1c,
	0x7f, 0x63, 0x08, 0x13, 0xa9, 0x94, 0x21, 0x6b, 0x1b, 0x6d, 0x6d, 0xac, 0xe5, 0xe8, 0x2d, 0x19,
	0xe9, 0xb4, 0xf9, 0x5a, 0x6d, 0x3e, 0xd3, 0xae, 0x91, 0x77, 0x50, 0xc5, 0x08, 0xe6, 0x86, 0xee,
	0xa4, 0x51, 0x0d, 0xe5, 0x15, 0xee, 0xd5, 0xf0, 0x15, 0xdc, 0xb7, 0x94, 0xdf, 0x5e, 0x39, 0xf9,
	0x23, 0x2b, 0xd3, 0x6f, 0x6c, 0x97, 0x45, 0x9e, 0x89, 0xe3, 0x46, 0xbd, 0xbd, 0x4d, 0xb4, 0x21,
	0x36, 0x36, 0x17, 0x3e, 0xe0, 0x4b, 0xb8, 0xf7, 0x0f, 0x7a, 0xc5, 0xc0, 0x84, 0x81, 0xa3, 0x7a,
	0xf4, 0x3b, 0x80, 0xc5, 0xa7, 0x46, 0x88, 0x20, 0x5b, 0xe5, 0x7c, 0xc3, 0xee, 0x9f, 0x62, 0x03,
	0xff, 0xb9, 0x61, 0x07, 0xe3, 0x1b, 0x98, 0x29, 0xca, 0x29, 0x95, 0xb5, 0xee, 0x01, 0xeb, 0x7e,
	0xd0, 0xeb, 0xee, 0xf4, 0x8a, 0x9e, 0xc2, 0x4b, 0x38, 0x6b, 0xc3, 0x0d, 0x5f, 0x69, 0xc8, 0xcf,
	0x70, 0xff, 0x4a, 0xf5, 0x21, 0xc5, 0x3e, 0xb8, 0x19, 0xf3, 0x2c, 0x6f, 0xff, 0x06, 0x00, 0x00,
	0xff, 0xff, 0xd6, 0x00, 0x66, 0x2f, 0x4b, 0x03, 0x00, 0x00,
}
