// Code generated by protoc-gen-go. DO NOT EDIT.
// source: election.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ElectionResultPb struct {
	Candidates           []string `protobuf:"bytes,1,rep,name=candidates,proto3" json:"candidates,omitempty"`
	Scores               [][]byte `protobuf:"bytes,2,rep,name=scores,proto3" json:"scores,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ElectionResultPb) Reset()         { *m = ElectionResultPb{} }
func (m *ElectionResultPb) String() string { return proto.CompactTextString(m) }
func (*ElectionResultPb) ProtoMessage()    {}
func (*ElectionResultPb) Descriptor() ([]byte, []int) {
	return fileDescriptor_election_de073fa00d97b2e0, []int{0}
}
func (m *ElectionResultPb) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ElectionResultPb.Unmarshal(m, b)
}
func (m *ElectionResultPb) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ElectionResultPb.Marshal(b, m, deterministic)
}
func (dst *ElectionResultPb) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ElectionResultPb.Merge(dst, src)
}
func (m *ElectionResultPb) XXX_Size() int {
	return xxx_messageInfo_ElectionResultPb.Size(m)
}
func (m *ElectionResultPb) XXX_DiscardUnknown() {
	xxx_messageInfo_ElectionResultPb.DiscardUnknown(m)
}

var xxx_messageInfo_ElectionResultPb proto.InternalMessageInfo

func (m *ElectionResultPb) GetCandidates() []string {
	if m != nil {
		return m.Candidates
	}
	return nil
}

func (m *ElectionResultPb) GetScores() [][]byte {
	if m != nil {
		return m.Scores
	}
	return nil
}

func init() {
	proto.RegisterType((*ElectionResultPb)(nil), "pb.ElectionResultPb")
}

func init() { proto.RegisterFile("election.proto", fileDescriptor_election_de073fa00d97b2e0) }

var fileDescriptor_election_de073fa00d97b2e0 = []byte{
	// 106 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4b, 0xcd, 0x49, 0x4d,
	0x2e, 0xc9, 0xcc, 0xcf, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x48, 0x52, 0xf2,
	0xe2, 0x12, 0x70, 0x85, 0x8a, 0x06, 0xa5, 0x16, 0x97, 0xe6, 0x94, 0x04, 0x24, 0x09, 0xc9, 0x71,
	0x71, 0x25, 0x27, 0xe6, 0xa5, 0x64, 0xa6, 0x24, 0x96, 0xa4, 0x16, 0x4b, 0x30, 0x2a, 0x30, 0x6b,
	0x70, 0x06, 0x21, 0x89, 0x08, 0x89, 0x71, 0xb1, 0x15, 0x27, 0xe7, 0x17, 0xa5, 0x16, 0x4b, 0x30,
	0x29, 0x30, 0x6b, 0xf0, 0x04, 0x41, 0x79, 0x49, 0x6c, 0x60, 0x63, 0x8d, 0x01, 0x01, 0x00, 0x00,
	0xff, 0xff, 0x94, 0xb1, 0x4e, 0x31, 0x68, 0x00, 0x00, 0x00,
}
