// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type HealthCheckResponse_Status int32

const (
	HealthCheckResponse_STARTING HealthCheckResponse_Status = 0
	HealthCheckResponse_ACTIVE   HealthCheckResponse_Status = 1
	HealthCheckResponse_INACTIVE HealthCheckResponse_Status = 2
)

var HealthCheckResponse_Status_name = map[int32]string{
	0: "STARTING",
	1: "ACTIVE",
	2: "INACTIVE",
}

var HealthCheckResponse_Status_value = map[string]int32{
	"STARTING": 0,
	"ACTIVE":   1,
	"INACTIVE": 2,
}

func (x HealthCheckResponse_Status) String() string {
	return proto.EnumName(HealthCheckResponse_Status_name, int32(x))
}

func (HealthCheckResponse_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{7, 0}
}

type ChainMeta struct {
	Height               string   `protobuf:"bytes,1,opt,name=height,proto3" json:"height,omitempty"`
	TotalCandidates      uint64   `protobuf:"varint,2,opt,name=totalCandidates,proto3" json:"totalCandidates,omitempty"`
	TotalVotedStakes     string   `protobuf:"bytes,3,opt,name=totalVotedStakes,proto3" json:"totalVotedStakes,omitempty"`
	TotalVotes           string   `protobuf:"bytes,4,opt,name=totalVotes,proto3" json:"totalVotes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChainMeta) Reset()         { *m = ChainMeta{} }
func (m *ChainMeta) String() string { return proto.CompactTextString(m) }
func (*ChainMeta) ProtoMessage()    {}
func (*ChainMeta) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{0}
}

func (m *ChainMeta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChainMeta.Unmarshal(m, b)
}
func (m *ChainMeta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChainMeta.Marshal(b, m, deterministic)
}
func (m *ChainMeta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChainMeta.Merge(m, src)
}
func (m *ChainMeta) XXX_Size() int {
	return xxx_messageInfo_ChainMeta.Size(m)
}
func (m *ChainMeta) XXX_DiscardUnknown() {
	xxx_messageInfo_ChainMeta.DiscardUnknown(m)
}

var xxx_messageInfo_ChainMeta proto.InternalMessageInfo

func (m *ChainMeta) GetHeight() string {
	if m != nil {
		return m.Height
	}
	return ""
}

func (m *ChainMeta) GetTotalCandidates() uint64 {
	if m != nil {
		return m.TotalCandidates
	}
	return 0
}

func (m *ChainMeta) GetTotalVotedStakes() string {
	if m != nil {
		return m.TotalVotedStakes
	}
	return ""
}

func (m *ChainMeta) GetTotalVotes() string {
	if m != nil {
		return m.TotalVotes
	}
	return ""
}

type Bucket struct {
	// hex string
	Voter         string `protobuf:"bytes,1,opt,name=voter,proto3" json:"voter,omitempty"`
	Votes         string `protobuf:"bytes,2,opt,name=votes,proto3" json:"votes,omitempty"`
	WeightedVotes string `protobuf:"bytes,3,opt,name=weightedVotes,proto3" json:"weightedVotes,omitempty"`
	// human readable duration
	RemainingDuration    string   `protobuf:"bytes,4,opt,name=remainingDuration,proto3" json:"remainingDuration,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Bucket) Reset()         { *m = Bucket{} }
func (m *Bucket) String() string { return proto.CompactTextString(m) }
func (*Bucket) ProtoMessage()    {}
func (*Bucket) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{1}
}

func (m *Bucket) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Bucket.Unmarshal(m, b)
}
func (m *Bucket) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Bucket.Marshal(b, m, deterministic)
}
func (m *Bucket) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Bucket.Merge(m, src)
}
func (m *Bucket) XXX_Size() int {
	return xxx_messageInfo_Bucket.Size(m)
}
func (m *Bucket) XXX_DiscardUnknown() {
	xxx_messageInfo_Bucket.DiscardUnknown(m)
}

var xxx_messageInfo_Bucket proto.InternalMessageInfo

func (m *Bucket) GetVoter() string {
	if m != nil {
		return m.Voter
	}
	return ""
}

func (m *Bucket) GetVotes() string {
	if m != nil {
		return m.Votes
	}
	return ""
}

func (m *Bucket) GetWeightedVotes() string {
	if m != nil {
		return m.WeightedVotes
	}
	return ""
}

func (m *Bucket) GetRemainingDuration() string {
	if m != nil {
		return m.RemainingDuration
	}
	return ""
}

type Candidate struct {
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// hex string
	Address              string   `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	TotalWeightedVotes   string   `protobuf:"bytes,3,opt,name=totalWeightedVotes,proto3" json:"totalWeightedVotes,omitempty"`
	SelfStakingTokens    string   `protobuf:"bytes,4,opt,name=selfStakingTokens,proto3" json:"selfStakingTokens,omitempty"`
	OperatorAddress      string   `protobuf:"bytes,5,opt,name=operatorAddress,proto3" json:"operatorAddress,omitempty"`
	RewardAddress        string   `protobuf:"bytes,6,opt,name=rewardAddress,proto3" json:"rewardAddress,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Candidate) Reset()         { *m = Candidate{} }
func (m *Candidate) String() string { return proto.CompactTextString(m) }
func (*Candidate) ProtoMessage()    {}
func (*Candidate) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{2}
}

func (m *Candidate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Candidate.Unmarshal(m, b)
}
func (m *Candidate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Candidate.Marshal(b, m, deterministic)
}
func (m *Candidate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Candidate.Merge(m, src)
}
func (m *Candidate) XXX_Size() int {
	return xxx_messageInfo_Candidate.Size(m)
}
func (m *Candidate) XXX_DiscardUnknown() {
	xxx_messageInfo_Candidate.DiscardUnknown(m)
}

var xxx_messageInfo_Candidate proto.InternalMessageInfo

func (m *Candidate) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Candidate) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Candidate) GetTotalWeightedVotes() string {
	if m != nil {
		return m.TotalWeightedVotes
	}
	return ""
}

func (m *Candidate) GetSelfStakingTokens() string {
	if m != nil {
		return m.SelfStakingTokens
	}
	return ""
}

func (m *Candidate) GetOperatorAddress() string {
	if m != nil {
		return m.OperatorAddress
	}
	return ""
}

func (m *Candidate) GetRewardAddress() string {
	if m != nil {
		return m.RewardAddress
	}
	return ""
}

type GetCandidatesRequest struct {
	Height               string   `protobuf:"bytes,1,opt,name=height,proto3" json:"height,omitempty"`
	Offset               uint32   `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit                uint32   `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCandidatesRequest) Reset()         { *m = GetCandidatesRequest{} }
func (m *GetCandidatesRequest) String() string { return proto.CompactTextString(m) }
func (*GetCandidatesRequest) ProtoMessage()    {}
func (*GetCandidatesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{3}
}

func (m *GetCandidatesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCandidatesRequest.Unmarshal(m, b)
}
func (m *GetCandidatesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCandidatesRequest.Marshal(b, m, deterministic)
}
func (m *GetCandidatesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCandidatesRequest.Merge(m, src)
}
func (m *GetCandidatesRequest) XXX_Size() int {
	return xxx_messageInfo_GetCandidatesRequest.Size(m)
}
func (m *GetCandidatesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCandidatesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetCandidatesRequest proto.InternalMessageInfo

func (m *GetCandidatesRequest) GetHeight() string {
	if m != nil {
		return m.Height
	}
	return ""
}

func (m *GetCandidatesRequest) GetOffset() uint32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *GetCandidatesRequest) GetLimit() uint32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type GetCandidateByNameRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Height               string   `protobuf:"bytes,2,opt,name=height,proto3" json:"height,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCandidateByNameRequest) Reset()         { *m = GetCandidateByNameRequest{} }
func (m *GetCandidateByNameRequest) String() string { return proto.CompactTextString(m) }
func (*GetCandidateByNameRequest) ProtoMessage()    {}
func (*GetCandidateByNameRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{4}
}

func (m *GetCandidateByNameRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCandidateByNameRequest.Unmarshal(m, b)
}
func (m *GetCandidateByNameRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCandidateByNameRequest.Marshal(b, m, deterministic)
}
func (m *GetCandidateByNameRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCandidateByNameRequest.Merge(m, src)
}
func (m *GetCandidateByNameRequest) XXX_Size() int {
	return xxx_messageInfo_GetCandidateByNameRequest.Size(m)
}
func (m *GetCandidateByNameRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCandidateByNameRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetCandidateByNameRequest proto.InternalMessageInfo

func (m *GetCandidateByNameRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GetCandidateByNameRequest) GetHeight() string {
	if m != nil {
		return m.Height
	}
	return ""
}

type GetBucketsByCandidateRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Height               string   `protobuf:"bytes,2,opt,name=height,proto3" json:"height,omitempty"`
	Offset               uint32   `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit                uint32   `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBucketsByCandidateRequest) Reset()         { *m = GetBucketsByCandidateRequest{} }
func (m *GetBucketsByCandidateRequest) String() string { return proto.CompactTextString(m) }
func (*GetBucketsByCandidateRequest) ProtoMessage()    {}
func (*GetBucketsByCandidateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{5}
}

func (m *GetBucketsByCandidateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBucketsByCandidateRequest.Unmarshal(m, b)
}
func (m *GetBucketsByCandidateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBucketsByCandidateRequest.Marshal(b, m, deterministic)
}
func (m *GetBucketsByCandidateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBucketsByCandidateRequest.Merge(m, src)
}
func (m *GetBucketsByCandidateRequest) XXX_Size() int {
	return xxx_messageInfo_GetBucketsByCandidateRequest.Size(m)
}
func (m *GetBucketsByCandidateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBucketsByCandidateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetBucketsByCandidateRequest proto.InternalMessageInfo

func (m *GetBucketsByCandidateRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GetBucketsByCandidateRequest) GetHeight() string {
	if m != nil {
		return m.Height
	}
	return ""
}

func (m *GetBucketsByCandidateRequest) GetOffset() uint32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *GetBucketsByCandidateRequest) GetLimit() uint32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type GetBucketsRequest struct {
	Height               string   `protobuf:"bytes,1,opt,name=height,proto3" json:"height,omitempty"`
	Offset               uint32   `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit                uint32   `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBucketsRequest) Reset()         { *m = GetBucketsRequest{} }
func (m *GetBucketsRequest) String() string { return proto.CompactTextString(m) }
func (*GetBucketsRequest) ProtoMessage()    {}
func (*GetBucketsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{6}
}

func (m *GetBucketsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBucketsRequest.Unmarshal(m, b)
}
func (m *GetBucketsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBucketsRequest.Marshal(b, m, deterministic)
}
func (m *GetBucketsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBucketsRequest.Merge(m, src)
}
func (m *GetBucketsRequest) XXX_Size() int {
	return xxx_messageInfo_GetBucketsRequest.Size(m)
}
func (m *GetBucketsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBucketsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetBucketsRequest proto.InternalMessageInfo

func (m *GetBucketsRequest) GetHeight() string {
	if m != nil {
		return m.Height
	}
	return ""
}

func (m *GetBucketsRequest) GetOffset() uint32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *GetBucketsRequest) GetLimit() uint32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type HealthCheckResponse struct {
	Status               HealthCheckResponse_Status `protobuf:"varint,1,opt,name=status,proto3,enum=api.HealthCheckResponse_Status" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *HealthCheckResponse) Reset()         { *m = HealthCheckResponse{} }
func (m *HealthCheckResponse) String() string { return proto.CompactTextString(m) }
func (*HealthCheckResponse) ProtoMessage()    {}
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{7}
}

func (m *HealthCheckResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HealthCheckResponse.Unmarshal(m, b)
}
func (m *HealthCheckResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HealthCheckResponse.Marshal(b, m, deterministic)
}
func (m *HealthCheckResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HealthCheckResponse.Merge(m, src)
}
func (m *HealthCheckResponse) XXX_Size() int {
	return xxx_messageInfo_HealthCheckResponse.Size(m)
}
func (m *HealthCheckResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HealthCheckResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HealthCheckResponse proto.InternalMessageInfo

func (m *HealthCheckResponse) GetStatus() HealthCheckResponse_Status {
	if m != nil {
		return m.Status
	}
	return HealthCheckResponse_STARTING
}

type CandidateResponse struct {
	Candidates           []*Candidate `protobuf:"bytes,1,rep,name=candidates,proto3" json:"candidates,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *CandidateResponse) Reset()         { *m = CandidateResponse{} }
func (m *CandidateResponse) String() string { return proto.CompactTextString(m) }
func (*CandidateResponse) ProtoMessage()    {}
func (*CandidateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{8}
}

func (m *CandidateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CandidateResponse.Unmarshal(m, b)
}
func (m *CandidateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CandidateResponse.Marshal(b, m, deterministic)
}
func (m *CandidateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CandidateResponse.Merge(m, src)
}
func (m *CandidateResponse) XXX_Size() int {
	return xxx_messageInfo_CandidateResponse.Size(m)
}
func (m *CandidateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CandidateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CandidateResponse proto.InternalMessageInfo

func (m *CandidateResponse) GetCandidates() []*Candidate {
	if m != nil {
		return m.Candidates
	}
	return nil
}

type BucketResponse struct {
	Buckets              []*Bucket `protobuf:"bytes,1,rep,name=buckets,proto3" json:"buckets,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *BucketResponse) Reset()         { *m = BucketResponse{} }
func (m *BucketResponse) String() string { return proto.CompactTextString(m) }
func (*BucketResponse) ProtoMessage()    {}
func (*BucketResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{9}
}

func (m *BucketResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BucketResponse.Unmarshal(m, b)
}
func (m *BucketResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BucketResponse.Marshal(b, m, deterministic)
}
func (m *BucketResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BucketResponse.Merge(m, src)
}
func (m *BucketResponse) XXX_Size() int {
	return xxx_messageInfo_BucketResponse.Size(m)
}
func (m *BucketResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BucketResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BucketResponse proto.InternalMessageInfo

func (m *BucketResponse) GetBuckets() []*Bucket {
	if m != nil {
		return m.Buckets
	}
	return nil
}

func init() {
	proto.RegisterEnum("api.HealthCheckResponse_Status", HealthCheckResponse_Status_name, HealthCheckResponse_Status_value)
	proto.RegisterType((*ChainMeta)(nil), "api.ChainMeta")
	proto.RegisterType((*Bucket)(nil), "api.Bucket")
	proto.RegisterType((*Candidate)(nil), "api.Candidate")
	proto.RegisterType((*GetCandidatesRequest)(nil), "api.GetCandidatesRequest")
	proto.RegisterType((*GetCandidateByNameRequest)(nil), "api.GetCandidateByNameRequest")
	proto.RegisterType((*GetBucketsByCandidateRequest)(nil), "api.GetBucketsByCandidateRequest")
	proto.RegisterType((*GetBucketsRequest)(nil), "api.GetBucketsRequest")
	proto.RegisterType((*HealthCheckResponse)(nil), "api.HealthCheckResponse")
	proto.RegisterType((*CandidateResponse)(nil), "api.CandidateResponse")
	proto.RegisterType((*BucketResponse)(nil), "api.BucketResponse")
}

func init() { proto.RegisterFile("api.proto", fileDescriptor_00212fb1f9d3bf1c) }

var fileDescriptor_00212fb1f9d3bf1c = []byte{
	// 658 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x54, 0x41, 0x6f, 0xd3, 0x4c,
	0x10, 0x8d, 0x9b, 0xd4, 0x6d, 0xa7, 0x5f, 0xfa, 0xb5, 0xdb, 0x12, 0xa5, 0x01, 0x95, 0x62, 0x81,
	0x14, 0x21, 0xe4, 0xa2, 0xf6, 0xd0, 0x03, 0x12, 0x52, 0x9a, 0x96, 0x90, 0x03, 0x15, 0x38, 0x51,
	0x11, 0x12, 0x97, 0x6d, 0x3c, 0x71, 0x56, 0x49, 0xbc, 0xc1, 0xbb, 0x69, 0xe9, 0x8d, 0x23, 0x7f,
	0x81, 0x13, 0x3f, 0x8f, 0xbf, 0x81, 0xbc, 0xbb, 0xae, 0x9d, 0xc4, 0x11, 0x12, 0xe2, 0x96, 0x79,
	0xfb, 0xfc, 0xe6, 0xcd, 0xdb, 0xc9, 0xc2, 0x06, 0x9d, 0x30, 0x77, 0x12, 0x71, 0xc9, 0x49, 0x91,
	0x4e, 0x58, 0xed, 0x61, 0xc0, 0x79, 0x30, 0xc2, 0x23, 0x05, 0x5d, 0x4f, 0xfb, 0x47, 0x38, 0x9e,
	0xc8, 0x3b, 0xcd, 0x70, 0x7e, 0x58, 0xb0, 0xd1, 0x1c, 0x50, 0x16, 0xbe, 0x43, 0x49, 0x49, 0x05,
	0xec, 0x01, 0xb2, 0x60, 0x20, 0xab, 0xd6, 0xa1, 0x55, 0xdf, 0xf0, 0x4c, 0x45, 0xea, 0xf0, 0xbf,
	0xe4, 0x92, 0x8e, 0x9a, 0x34, 0xf4, 0x99, 0x4f, 0x25, 0x8a, 0xea, 0xca, 0xa1, 0x55, 0x2f, 0x79,
	0xf3, 0x30, 0x79, 0x0e, 0xdb, 0x0a, 0xba, 0xe2, 0x12, 0xfd, 0x8e, 0xa4, 0x43, 0x14, 0xd5, 0xa2,
	0xd2, 0x5a, 0xc0, 0xc9, 0x01, 0xc0, 0x3d, 0x26, 0xaa, 0x25, 0xc5, 0xca, 0x20, 0xce, 0x77, 0x0b,
	0xec, 0xb3, 0x69, 0x6f, 0x88, 0x92, 0xec, 0xc1, 0xea, 0x0d, 0x97, 0x18, 0x19, 0x5f, 0xba, 0x48,
	0x50, 0x6d, 0xc6, 0xa0, 0x82, 0x3c, 0x85, 0xf2, 0xad, 0xb2, 0x8d, 0xbe, 0x56, 0xd6, 0xfd, 0x67,
	0x41, 0xf2, 0x02, 0x76, 0x22, 0x1c, 0x53, 0x16, 0xb2, 0x30, 0x38, 0x9f, 0x46, 0x54, 0x32, 0x1e,
	0x1a, 0x0f, 0x8b, 0x07, 0xce, 0xaf, 0x38, 0xa6, 0x64, 0x4a, 0x42, 0xa0, 0x14, 0xd2, 0x31, 0x1a,
	0x33, 0xea, 0x37, 0xa9, 0xc2, 0x1a, 0xf5, 0xfd, 0x08, 0x45, 0xe2, 0x26, 0x29, 0x89, 0x0b, 0x44,
	0x0d, 0xf5, 0x31, 0xc7, 0x54, 0xce, 0x49, 0xec, 0x4c, 0xe0, 0xa8, 0x1f, 0x87, 0xc4, 0xc2, 0xa0,
	0xcb, 0x87, 0x18, 0x26, 0xe9, 0x2c, 0x1e, 0xc4, 0x57, 0xc3, 0x27, 0x18, 0x51, 0xc9, 0xa3, 0x86,
	0xe9, 0xbf, 0xaa, 0xb8, 0xf3, 0x70, 0x9c, 0x4b, 0x84, 0xb7, 0x34, 0xf2, 0x13, 0x9e, 0xad, 0x73,
	0x99, 0x01, 0x9d, 0xcf, 0xb0, 0xd7, 0x42, 0x99, 0xde, 0xa8, 0x87, 0x5f, 0xa6, 0x28, 0xe4, 0xd2,
	0xd5, 0xa8, 0x80, 0xcd, 0xfb, 0x7d, 0x81, 0x52, 0x8d, 0x5d, 0xf6, 0x4c, 0x15, 0xdf, 0xcd, 0x88,
	0x8d, 0x99, 0x54, 0x83, 0x96, 0x3d, 0x5d, 0x38, 0x2d, 0xd8, 0xcf, 0xaa, 0x9f, 0xdd, 0x5d, 0xd2,
	0x31, 0x26, 0x2d, 0xf2, 0x62, 0x4d, 0xdb, 0xae, 0x64, 0xdb, 0x3a, 0x5f, 0xe1, 0x51, 0x0b, 0xa5,
	0xde, 0x0e, 0x71, 0x76, 0x77, 0xaf, 0xf8, 0x17, 0x5a, 0x99, 0x11, 0x8a, 0xf9, 0x23, 0x94, 0xb2,
	0x23, 0x7c, 0x82, 0x9d, 0xb4, 0xf3, 0xbf, 0x4d, 0xe7, 0x9b, 0x05, 0xbb, 0x6f, 0x91, 0x8e, 0xe4,
	0xa0, 0x39, 0xc0, 0xde, 0xd0, 0x43, 0x31, 0xe1, 0xa1, 0x40, 0x72, 0x0a, 0xb6, 0x90, 0x54, 0x4e,
	0x85, 0x52, 0xdf, 0x3a, 0x7e, 0xec, 0xc6, 0x7f, 0xf1, 0x1c, 0xa6, 0xdb, 0x51, 0x34, 0xcf, 0xd0,
	0x9d, 0x97, 0x60, 0x6b, 0x84, 0xfc, 0x07, 0xeb, 0x9d, 0x6e, 0xc3, 0xeb, 0xb6, 0x2f, 0x5b, 0xdb,
	0x05, 0x02, 0x60, 0x37, 0x9a, 0xdd, 0xf6, 0xd5, 0xc5, 0xb6, 0x15, 0x9f, 0xb4, 0x2f, 0x4d, 0xb5,
	0xe2, 0x34, 0x61, 0x27, 0x93, 0xa5, 0xe9, 0xef, 0x02, 0xf4, 0xd2, 0x7f, 0xbe, 0x75, 0x58, 0xac,
	0x6f, 0x1e, 0x6f, 0x29, 0x0f, 0x29, 0x37, 0xc3, 0x70, 0x4e, 0x61, 0x4b, 0xe7, 0x73, 0xaf, 0xf0,
	0x0c, 0xd6, 0xae, 0x75, 0x62, 0xe6, 0xf3, 0x4d, 0xf5, 0xb9, 0x61, 0x25, 0x67, 0xc7, 0x3f, 0x8b,
	0x00, 0x8d, 0xf7, 0xed, 0x0e, 0x46, 0x37, 0xac, 0x87, 0xe4, 0x04, 0xd6, 0x02, 0x94, 0xfa, 0x65,
	0x72, 0xf5, 0x2b, 0xe6, 0x26, 0xaf, 0x98, 0x7b, 0x11, 0xbf, 0x62, 0x35, 0x63, 0x23, 0x79, 0xc1,
	0x9c, 0x02, 0x39, 0x87, 0x72, 0x90, 0x5d, 0x60, 0xb2, 0xaf, 0x28, 0x79, 0x4b, 0x5d, 0xab, 0xcc,
	0x0d, 0x61, 0xec, 0x3a, 0x05, 0xf2, 0x06, 0x48, 0xb0, 0xb0, 0xa8, 0xe4, 0x60, 0x41, 0x6a, 0x66,
	0x83, 0x6b, 0x73, 0xa1, 0x38, 0x05, 0xf2, 0x01, 0x1e, 0x04, 0x79, 0x7b, 0x4a, 0x9e, 0x24, 0x52,
	0x4b, 0x77, 0xb8, 0xb6, 0x9b, 0xcd, 0x28, 0xb5, 0xf6, 0x0a, 0x20, 0x95, 0x24, 0x95, 0x39, 0x9d,
	0x3f, 0x7c, 0xfc, 0x1a, 0xd6, 0x99, 0xd0, 0x9b, 0xb3, 0x34, 0xd3, 0xea, 0xb2, 0xf5, 0x72, 0x0a,
	0xd7, 0xb6, 0xe2, 0x9e, 0xfc, 0x0e, 0x00, 0x00, 0xff, 0xff, 0xba, 0x07, 0x5f, 0x89, 0x65, 0x06,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// APIServiceClient is the client API for APIService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type APIServiceClient interface {
	// get the blockchain meta data
	GetMeta(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*ChainMeta, error)
	// get candidates
	GetCandidates(ctx context.Context, in *GetCandidatesRequest, opts ...grpc.CallOption) (*CandidateResponse, error)
	// get candidate by name
	GetCandidateByName(ctx context.Context, in *GetCandidateByNameRequest, opts ...grpc.CallOption) (*Candidate, error)
	// get buckets by candidate
	GetBucketsByCandidate(ctx context.Context, in *GetBucketsByCandidateRequest, opts ...grpc.CallOption) (*BucketResponse, error)
	// get Buckets
	GetBuckets(ctx context.Context, in *GetBucketsRequest, opts ...grpc.CallOption) (*BucketResponse, error)
	// health endpoint
	IsHealth(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*HealthCheckResponse, error)
}

type aPIServiceClient struct {
	cc *grpc.ClientConn
}

func NewAPIServiceClient(cc *grpc.ClientConn) APIServiceClient {
	return &aPIServiceClient{cc}
}

func (c *aPIServiceClient) GetMeta(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*ChainMeta, error) {
	out := new(ChainMeta)
	err := c.cc.Invoke(ctx, "/api.APIService/getMeta", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIServiceClient) GetCandidates(ctx context.Context, in *GetCandidatesRequest, opts ...grpc.CallOption) (*CandidateResponse, error) {
	out := new(CandidateResponse)
	err := c.cc.Invoke(ctx, "/api.APIService/getCandidates", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIServiceClient) GetCandidateByName(ctx context.Context, in *GetCandidateByNameRequest, opts ...grpc.CallOption) (*Candidate, error) {
	out := new(Candidate)
	err := c.cc.Invoke(ctx, "/api.APIService/getCandidateByName", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIServiceClient) GetBucketsByCandidate(ctx context.Context, in *GetBucketsByCandidateRequest, opts ...grpc.CallOption) (*BucketResponse, error) {
	out := new(BucketResponse)
	err := c.cc.Invoke(ctx, "/api.APIService/getBucketsByCandidate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIServiceClient) GetBuckets(ctx context.Context, in *GetBucketsRequest, opts ...grpc.CallOption) (*BucketResponse, error) {
	out := new(BucketResponse)
	err := c.cc.Invoke(ctx, "/api.APIService/getBuckets", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIServiceClient) IsHealth(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, "/api.APIService/isHealth", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// APIServiceServer is the server API for APIService service.
type APIServiceServer interface {
	// get the blockchain meta data
	GetMeta(context.Context, *empty.Empty) (*ChainMeta, error)
	// get candidates
	GetCandidates(context.Context, *GetCandidatesRequest) (*CandidateResponse, error)
	// get candidate by name
	GetCandidateByName(context.Context, *GetCandidateByNameRequest) (*Candidate, error)
	// get buckets by candidate
	GetBucketsByCandidate(context.Context, *GetBucketsByCandidateRequest) (*BucketResponse, error)
	// get Buckets
	GetBuckets(context.Context, *GetBucketsRequest) (*BucketResponse, error)
	// health endpoint
	IsHealth(context.Context, *empty.Empty) (*HealthCheckResponse, error)
}

func RegisterAPIServiceServer(s *grpc.Server, srv APIServiceServer) {
	s.RegisterService(&_APIService_serviceDesc, srv)
}

func _APIService_GetMeta_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServiceServer).GetMeta(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.APIService/GetMeta",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServiceServer).GetMeta(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _APIService_GetCandidates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCandidatesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServiceServer).GetCandidates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.APIService/GetCandidates",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServiceServer).GetCandidates(ctx, req.(*GetCandidatesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _APIService_GetCandidateByName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCandidateByNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServiceServer).GetCandidateByName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.APIService/GetCandidateByName",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServiceServer).GetCandidateByName(ctx, req.(*GetCandidateByNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _APIService_GetBucketsByCandidate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBucketsByCandidateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServiceServer).GetBucketsByCandidate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.APIService/GetBucketsByCandidate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServiceServer).GetBucketsByCandidate(ctx, req.(*GetBucketsByCandidateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _APIService_GetBuckets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBucketsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServiceServer).GetBuckets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.APIService/GetBuckets",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServiceServer).GetBuckets(ctx, req.(*GetBucketsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _APIService_IsHealth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServiceServer).IsHealth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.APIService/IsHealth",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServiceServer).IsHealth(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _APIService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.APIService",
	HandlerType: (*APIServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "getMeta",
			Handler:    _APIService_GetMeta_Handler,
		},
		{
			MethodName: "getCandidates",
			Handler:    _APIService_GetCandidates_Handler,
		},
		{
			MethodName: "getCandidateByName",
			Handler:    _APIService_GetCandidateByName_Handler,
		},
		{
			MethodName: "getBucketsByCandidate",
			Handler:    _APIService_GetBucketsByCandidate_Handler,
		},
		{
			MethodName: "getBuckets",
			Handler:    _APIService_GetBuckets_Handler,
		},
		{
			MethodName: "isHealth",
			Handler:    _APIService_IsHealth_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}
